### ISSUE TITLE
Move Hacktoberfest files

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#107]
Markdown files for Hacktoberfest are currently located under the `.github` folder hierarchy.  Please move it from there to either the root folder of the documentation repo, or the wiki repository for the documentation.

**Comment by unnati914** [comment]
I can work on this

**Comment by joewxboy** [comment]
Let's also make sure we spell `Hacktoberfest` consistently in the document.  Are you able to get to this today, or should I scrub in a fix it?

**Comment by joewxboy** [comment]
File moved to project wiki.  This page is no longer needed.
