### ISSUE TITLE
How to update constraint of an existing deployment policy via hzn cli?

### ISSUE THREAD

**Issue by lee-zhg** [open-horizon/open-horizon.github.io#114]
There are couple of options to update constraint of an existing deployment policy via hzn cli.

1) hzn exchange business updatepolicy ${POLICY} -f ${UPDATE_POLICY_FILE}

where the UPDATE_POLICY_FILE contains something like
{
  "constraints": [
    "quay_horizon_model_100 >= 1000"
  ]
}

2) hzn exchange deployment addpolicy --json-file=${POLICY_FILE_WITH_UPDATE} ${POLICY}

Note, "hzn exchange deployment updatepolicy --json-file=${POLICY_FILE_WITH_UPDATE} ${POLICY}" only updates the policy attributes and ignore any constraint update.

**Comment by Sukriti-sood** [comment]
@joewxboy I wanted to work on this

**Comment by joewxboy** [comment]
Sorry, @Sukriti-sood I didn't see that you requested this one.

**Comment by johnwalicki** [comment]
Opened a new issue to move this FAQ entry.  #226
