### ISSUE TITLE
Updating node with new service version

### ISSUE THREAD

**Issue by jsaez-ibm** [open-horizon/open-horizon.github.io#118]
How do you update a service running on a node with a newer (latest) version of the service?

**Comment by joewxboy** [comment]
@jsaez-ibm We're searching to see if there are existing documentation pages that cover this topic.  In the meantime, the specific answer from @TheMosquito is:

1. Make and publish a new version of the service, ideally updating the version
2. Update the existing Service Definition file and publish it
3. Edit pattern or policy to change the version number, and republish it

**Comment by Abhijay007** [comment]
@joewxboy do we got any existing documentation pages that cover this topic? or can we go further with the answer suggested by @TheMosquito and add that to the docs?

**Comment by johnwalicki** [comment]
Glen's comment is correct.  That's how I deploy updated Service containers to edge nodes.

Maybe we need a Common Use Cases page in the Developing section?

**Comment by Abhijay007** [comment]
> Glen's comment is correct. That's how I deploy updated Service containers to edge nodes.
> 
> Maybe we need a Common Use Cases page in the Developing section?

ya we can add one

**Comment by joewxboy** [comment]
This is now documented several places.  In https://open-horizon.github.io/docs/using_edge_services/service_rollbacks/#creating_edge_service_definition it states:

the main steps to release a new version of an edge service are:

1. Edit the edge service code as needed for the new version.
2. Edit the semantic version number of the code in the service version variable in the hzn.json configuration file.
3. Rebuild your service containers.
4. Sign and publish the new edge service version into the Horizon exchange.
