### ISSUE TITLE
Broken link https://open-horizon.github.io/docs/admin/backup_recovery.md

### ISSUE THREAD

**Issue by playground** [open-horizon/open-horizon.github.io#119]
Looks like backup_recovery.md file is missing.

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Rene-Ch1 @joewxboy

**Comment by joewxboy** [comment]
Go ahead, @Akshit42-hue 

Post a comment or message in the chat room if you have any questions.  Don't forget to:

1. Sign off on the commit (-s or --sign-off)
2. Name the PR beginning with `Issue-119: `

**Comment by Akshit42-hue** [comment]
I think all the links are accessible @joewxboy
