### ISSUE TITLE
Conditionalize OH/IEAM content in shared files

### ISSUE THREAD

**Issue by Rene-Ch1** [open-horizon/open-horizon.github.io#124]
In this issue, shared content refers to documentation files that reside in the OH repo, but are also embedded in the IEAM doc content (AKA - KC).

To accomplish this, we need to create a new yml file (proposed name - support.yml) to enable us to generate customized output: based on different operating systems and/or architecture. Labels/variables will control whether content is generated or blocked in the OH and IEAM doc output.

Updates are needed in the keyword.yml [file ](https://github.com/open-horizon/open-horizon.github.io/blob/master/_data/keyword.yml)too. 

As of 11/17/21, these files reside in the OH repo, but are also embedded in the IEAM content:

1. getting_started/overview_sm.md
2. developing/developing.md
3. developing/developing_secrets.md
4. developing/model_management_details.md
5. developing/secrets_details.md
6. developing/developing_details.md
7. developing/best_practices.md
8. user_management/security_privacy.md
9. api/index.md
10. api/agbot_api.md

**Comment by joewxboy** [comment]
Probably not needed, closing.
