### ISSUE TITLE
Create header and footer includes and apply to layouts

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#13]
Create Jekyll includes for page header and footer.  Then use in the layouts.  The information for the footer is currently hard-coded in the home layout.  The header should include the project logo.

**Comment by acostry** [comment]
@joewxboy Where to get the open-horizon project icon, logo, etc. ?

**Comment by joewxboy** [comment]
It's in the artwork repository: https://github.com/open-horizon/artwork

**Comment by acostry** [comment]
Thanks. @joewxboy I'd like to take this one.

**Comment by xiuleiyy** [comment]
This issue can be closed. Thanks @joewxboy

**Comment by joewxboy** [comment]
Confirmed, completed with merge of PR #17 .  Closing.
