### ISSUE TITLE
Improve the size and UI of the website

### ISSUE THREAD

**Issue by Ayush7614** [open-horizon/open-horizon.github.io#135]
We can increase the Navbar Size it is very small in size and looks not very good so i am working on it please assign me this issue

**Comment by Ayush7614** [comment]
![image](https://user-images.githubusercontent.com/67006255/152669566-359c512f-8397-43fd-852f-f113cafea6a5.png)

**Comment by Ayush7614** [comment]
@joewxboy ?

**Comment by joewxboy** [comment]
Thanks, @Ayush7614 .  One of our goals is to make the site responsive ... meaning that it appears differently depending on your device and screen size.  For example, we don't use hover actions on devices with a touch screen like tablets and mobile phones.  So any changes you make should be tested on actual devices on emulated on those devices in a desktop browser.  Let me know if you need any assistance in that regard.  Thanks.

Also, a great way to interact with the team is in our chat rooms, if you can join us there: https://chat.lfx.linuxfoundation.org/

**Comment by joewxboy** [comment]
@Abhijay007 Would this be addressed automatically by using a CDS-based template for Jekyll/GitHub Pages?

**Comment by joewxboy** [comment]
This has beed fixed in a different PR, closing.
