### ISSUE TITLE
Add GitHub Bots to Open-Horizon Repositories

### ISSUE THREAD

**Issue by Ayush7614** [open-horizon/open-horizon.github.io#138]
We need to have project-specific bots later (Especially for Go, Python, and JS-based projects) to track code quality, builds and all. Please have a look and let me know what you think. You can also add more bot integrations that we can have right here.

This issue would be used to track the integration of GitHub Bots across Open-Horizon repositories.

1 . Stale Bot  [Integration](https://github.com/apps/stale)
* Closes Issues and Pull Requests if not attended to in a specified period of time
* Maintains the overall sanctity of the issues and Pull Requests tab.
*  Keeps a check on spam/unnecessary Issues and PRs.

2 . Greet Bot [Integration](https://github.com/actions/first-interaction)
* Greet First Time Contributors

3 . Request - Info [Integration](https://github.com/apps/request-info)
* Request for the information if the issues/PR Content body is empty
*  Help us in Spam / invalid issues and PRs

We can also add many bots i have more specific bots and i can also add in the future
What is the idea cc @joewxboy  ?

**Comment by joewxboy** [comment]
@Ayush7614 This is great stuff!  Let me think about it.  There's still a lot I'm learning about GHAs.

Let me know (PM on chat server or email me) if you'd like to have a call (Facetime or Zoom or Skype or Google Meet or whatever) to discuss.

**Comment by Ayush7614** [comment]
> @Ayush7614 This is great stuff! Let me think about it. There's still a lot I'm learning about GHAs.
> 
> Let me know (PM on chat server or email me) if you'd like to have a call (Facetime or Zoom or Skype or Google Meet or whatever) to discuss.

Thanku @joewxboy Sure I am doing text on server to you and one thing is that should i start working on these

**Comment by Abhijay007** [comment]
@Ayush7614 are you still working on this?

**Comment by johnwalicki** [comment]
I'm not a fan of StaleBot.  Just because an issue is old does not mean it should be closed.

The others are nice to have, but somewhat unnecessary.  I could be convinced if there is valid case.  Open to suggestions.

I added ImgBot yesterday to squash image sizes.  That will prove to be helpful.

**Comment by joewxboy** [comment]
We've deployed several bots now, I think this can safely be closed.  Please comment here if I missed anything.
