### ISSUE TITLE
Add "Click to copy functionality" for commands on FAQ page

### ISSUE THREAD

**Issue by Abhijay007** [open-horizon/open-horizon.github.io#139]
**Describe the bug**

When the user goes to the FAQ page, the user doesn't have the ability to copy those commands by clicking on the commands. 

**Expected behavior**

The command should be copied when the user clicks on those commands.

**Screenshots**

![image](https://user-images.githubusercontent.com/64387054/153419501-9d806309-6dae-474c-af4f-9e9932d5e0cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : chrome

**Comment by Abhijay007** [comment]
@unnati914  @joewxboy can I work on this issue?

**Comment by joewxboy** [comment]
@Abhijay007 Take a look at how we implemented it on this page: https://open-horizon.github.io/quick-start

When you commit, don't forget to add the sign-off flag.

When you create a PR, begin the title with `Issue-139: `

**Comment by joewxboy** [comment]
BTW, if there's a better way to do it than what is already done, let's update the component so it's improved everywhere.

**Comment by Abhijay007** [comment]
> BTW, if there's a better way to do it than what is already done, let's update the component so it's improved everywhere.

got it :)
