### ISSUE TITLE
Update Open Graph image metadata in website

### ISSUE THREAD

**Issue by rithSubhro** [open-horizon/open-horizon.github.io#140]
## Description
In the website [open-horizon.github.io ](https://open-horizon.github.io/) meta og image is not  open horizon logo, I think its better to have an open horizon logo instead of  this -> https://github.com/open-horizon/open-horizon.github.io/blob/master/img/hero-dark.jpg

![Capture 7PNG](https://user-images.githubusercontent.com/68465693/153466808-d879b646-dbf9-4fa5-9eda-6ee5b587d080.PNG)

## References
Use https://developers.facebook.com/tools/debug/ to validate results for Facebook.
Use https://www.linkedin.com/post-inspector/ to validate results for LinkedIn.
Use https://cards-dev.twitter.com/validator to validate results for Twitter.

**Comment by joewxboy** [comment]
@rithSubhro Good point.  We haven't done any SEO validation, nor validated any of the `meta` tags (FB, twitter, etc).  If you spot anything else amiss, please comment in this issue.  Do you have the public URLs for our project artwork?

**Comment by rithSubhro** [comment]
Ya @joewxboy I went through the website  and got the lighthouse score

![image](https://user-images.githubusercontent.com/68465693/153474744-038ee665-0872-4b95-9db4-de30d9a17203.png)

I think we can improve a lot in the performance section, like we can can change all the current image formats to `.webp` format.

Implementing this will help in making consistency across the images and also since WebP lossless images are smaller in size than PNGs and other image formats so will enhance the rendering.

I tried converting the image locally using [cwep](https://developers.google.com/speed/webp/docs/using). It is a WebP encoder that can be invoked with the cwebp command.

I am trying to write a simple UNIX script to convert other image extensions to .webp format with the same file name. wdyt about this approach?

**Comment by joewxboy** [comment]
Hmm, an overall Lighthouse score of 80 was better than I expected. :)

My impression of `.webp` is that it's not supported by all browsers, so you'd have to use an imgsrc hack to fall back to other formats.  Sounds like a lot of complexity and extra maintenance.  A trade-off would be to convert the images to JPG or GIF depending on whether or not the image used transparency and whether or not it was a continuous tone image.  The only time we'd absolutely need to use PNG format is if we're taking advantage of alpha transparency effects.

**Comment by joewxboy** [comment]
SVG works quite well for logos and other vector images that can be almost any size.

**Comment by rithSubhro** [comment]
Ok so we don't need any updates in image formats as of now, so I can continue fixing the og meta image right? @joewxboy

**Comment by rithSubhro** [comment]
Yeah @joewxboy  sure also I think safari got support for webp too https://www.macrumors.com/2020/06/22/webp-safari-14/ so I guess now most of the browsers have support for webp so we can have a discussion on this later.

**Comment by Abhijay007** [comment]
@joewxboy I think @rithSubhro is quite busy or maybe active on this issue, can I resolve this?

**Comment by rithSubhro** [comment]
I have unassigned myself, all yours...

**Comment by Abhijay007** [comment]
> I have unassigned myself, all yours...

if you need any help I can assist :)
