### ISSUE TITLE
Bug🐛: Docs Page is not responsive for Mobile Devices 

### ISSUE THREAD

**Issue by Abhijay007** [open-horizon/open-horizon.github.io#141]
### Describe the bug.

The Docs page is not responsive on the mobile device, it is occupying some extra space on the right-hand side of the page

### Describe the steps to reproduce the behavior

1. go to the site
2. go to the docs page
3. use chrome dev tools to switch between different mobile screens !!

### Expected behavior.

the page should be responsive 

### Screenshots.

![image](https://user-images.githubusercontent.com/64387054/153560536-28f272d0-2701-4bdb-8323-054799559bc1.png)

### Operating environment

Windows 11

**Comment by Abhijay007** [comment]
@joewxboy can I work on it ?

**Comment by joewxboy** [comment]
It looks like this is related to https://github.com/open-horizon/open-horizon.github.io/issues/135 and the conversation in the chat room about Jekyll templates: https://matrix.to/#/!tUVxmZVqTyIhSrlIjN:chat.lfx.linuxfoundation.org/$m88-vwWE7VELf0lz1fvQRV8MIK2zc7e4n4gD6qF-nkw?via=chat.lfx.linuxfoundation.org&via=matrix.org

All three should be fix-able by replacing the current `tactile` template. Is Subhro Majumder actively working on that effort, and is there an issue for it?  If so, then this issue and issue 135 should be listed as dependencies of that one.

**Comment by Abhijay007** [comment]
> It looks like this is related to #135 and the conversation in the chat room about Jekyll templates: https://matrix.to/#/!tUVxmZVqTyIhSrlIjN:chat.lfx.linuxfoundation.org/$m88-vwWE7VELf0lz1fvQRV8MIK2zc7e4n4gD6qF-nkw?via=chat.lfx.linuxfoundation.org&via=matrix.org
> 
> All three should be fix-able by replacing the current `tactile` template. Is Subhro Majumder actively working on that effort, and is there an issue for it? If so, then this issue and issue 135 should be listed as dependencies of that one.

ok will look into that :)

**Comment by Amishakumari544** [comment]
Hi @Abhijay007 Can I work on this Issue?

**Comment by 03amir** [comment]
Can I work on this issue?

**Comment by joewxboy** [comment]
@03amir Take a look at the code and discussion and let me know what approach you'd like to take.

**Comment by 03amir** [comment]
@joewxboy  We can use media query and add a custom font size for the element which is causing this issue. And there is an extra margin, we can also remove that by a media query.

**Comment by johnwalicki** [comment]
Great suggestion @03amir - Which files would need to be modified to do the media query?

**Comment by 03amir** [comment]
@johnwalicki I think it would be the cynman.css file. Can we add some new classes to the element?

**Comment by johnwalicki** [comment]
@03amir OK, great. Yes, add more classes.

**Comment by 03amir** [comment]
@johnwalicki  Can you please assign me the issue?

**Comment by johnwalicki** [comment]
https://github.com/open-horizon/open-horizon.github.io/blob/master/css/cayman.css

**Comment by johnwalicki** [comment]
Closed by PR #310
