### ISSUE TITLE
Feature Idea: metrics to track usage of documentation site

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#142]
Goal: Understand how documentation is being used:

* Commonly-viewed pages
* Common referrers
* Where a person is, and what organization they belong to or who their ISP is
* Most common paths, user journeys

May also need: feedback opportunity on pages (didn't find what you were looking for), edit this page in github

What I don't want to do is slap a Google Analytics tag on the page and call it a day.  There are many competing tools out there and LFX may provide some services that fill this need.  If they don't, we should give them this feedback.  Also consider using the same tool on the project web site.

This issue is just capturing ideas and thoughts, and is not actionable.

**Comment by Ruchip16** [comment]
@joewxboy How about if we integrate Vercel lighthouse CLI to track the performance and usage of our docs

**Comment by joewxboy** [comment]
I'm only familiar with the Chrome Lighthouse plug-in, but I'm open to the options.

There is a strong correlation between visits to a site and page (and rendering) performance, so I'm open to tracking these together if it makes sense.

**Comment by Ruchip16** [comment]
![image](https://user-images.githubusercontent.com/72685035/153807973-64d03602-763d-473d-87c8-a2e2ac709bc7.png)
after running the chrome lighthouse tool these were the results I think we could work upon the areas for better improvement as per the changes suggested by report

**Comment by Ruchip16** [comment]
> I'm only familiar with the Chrome Lighthouse plug-in, but I'm open to the options.
> 
> There is a strong correlation between visits to a site and page (and rendering) performance, so I'm open to tracking these together if it makes sense.

yes, we can add performance and lighthouse workflow like performance workflow - it would add build-time performance action and lighthouse workflow - every time a PR gets raised it would generate a score for factors like SEO, performance, best practices & accessibility

**Comment by Abhijay007** [comment]
@Ruchip16 I think that lighthouse is more focused on SEO, performance, and optimization of the site and also produce reports accordingly, and as @joewxboy mentioned in the description above we need data or reports on Commonly-viewed pages, Common referrers, Where a person is, and what organization they belong to or who their ISP is, etc. 

I think Microsoft clarity is a better option as it shows us recorded video of user activity and provide us dedicated report on user hot-clicks etc, but as joe also mentioned we don't need tools like that so we need to find a better alternative that provides us data and produce reports on the basis of description provided, 

I think the best way to achieve this is to divide different use cases and find solutions for each one by one. like we can first start with the links that clicked most and what are the docs or resources that a user visited most and according to those reports we can sort the site and display the most used resource in a better and more accessible way :) 

I want to know your thoughts on this, do you think that this approach will help us?

**Comment by Ruchip16** [comment]
@Abhijay007 Yaa dividing different use cases and working on each one seems a better option also yes I re-read all the msgs and I get your point

**Comment by Abhijay007** [comment]
> @Abhijay007 Yaa dividing different use cases and working on each one seems a better option also yes I re-read all the msgs and I get your point but ig adding performance workflow would give us a better idea on the usage and performance of our docs during build time, what you think about this @Abhijay007 ?

@Ruchip16 can you please elaborate more on performance workflow?

**Comment by Ruchip16** [comment]
@Abhijay007 performance workflow will basically check the performance of any PR made during build time and will precheck for the dependencies, stability and speed of the code so whatever code gets merged into the docs would have already been tested on its performance and hence it would in turn lead to overall better performance of the docs. 
Again this is completely my opinion and would definitely love to hear others opinion on this as well.

**Comment by Abhijay007** [comment]
> @Abhijay007 performance workflow will basically check the performance of any PR made during build time and will precheck for the dependencies, stability and speed of the code so whatever code gets merged into the docs would have already been tested on its performance and hence it would in turn lead to overall better performance of the docs. Again this is completely my opinion and would definitely love to hear others opinion on this as well.

Thanks, @Ruchip16 for sharing about this 👍, I noticed that whenever I open a PR I get some run failed errors messages via mail which are related to `good-write.yml` and `config.yml` in workflows maybe we need to fix them too.

**Comment by Ruchip16** [comment]
@Abhijay007 exactly my point!

**Comment by Sukriti-sood** [comment]
@joewxboy For the feedback we can add small icon/buttom  in header/fotter  which will redirect to user to create issue in the repo. This [link](https://github.com/open-horizon/open-horizon.github.io/issues/new/choose)

**Comment by Sukriti-sood** [comment]
@joewxboy  That's a better approach, but I want to mention that most of the pages on the website have "Open Horizon" as the title, so I have filed an [issue](https://github.com/open-horizon/open-horizon.github.io/issues/151) covering both these things since they are mostly interconnected. Please assign me if you find this relevant. I would like to work on it otherwise give feedback.

**Comment by joewxboy** [comment]
> @joewxboy That's a better approach, but I want to mention that most of the pages on the website have "Open Horizon" as the title, so I have filed an [issue](https://github.com/open-horizon/open-horizon.github.io/issues/151) covering both these things since they are mostly interconnected. Please assign me if you find this relevant. I would like to work on it otherwise give feedback.

Very good point,  I'm glad you brought it up.  It brings to mind the concept of a title _stem_ or _root_ (as opposed to the "full" title).  We'd want to use the most specific part of the full title in breadcrumbs and in that issue link (and probably other places).

**Comment by johnwalicki** [comment]
@joewxboy  I think this issue is outdated because of the migration to the new theme ?

**Comment by joewxboy** [comment]
Here's the documentation for[ integrating Google Analytics 4](https://just-the-docs.github.io/just-the-docs/docs/configuration/#google-analytics) with Just the Docs.  This is what I'll try.
