### ISSUE TITLE
Documentation📄: Add Possible Errors that users can face. 

### ISSUE THREAD

**Issue by Abhijay007** [open-horizon/open-horizon.github.io#149]
### What is the current documentation state?

Add all the Possible errors that users can face while contributing or setting up a project locally on their machines by adding a separate section in the readme.MD file with the respected solutions. It will help newcomers to resolve possible errors by reading the docs we have. 

### Why do you want to improve the statement?

It is important as sometimes new contributors and users are not able to find any particular solutions to some errors and are not able to get help from the community as well, but if we mention all the errors that other community members and contributors have come across during the setup of the project or running it locally then it will very helpful for them !!

### Proposed Statement

we can achieve this by making a separate section in the readme.MD under contributing sections by naming it "possible errors" or "errors you may come across"

### Additional context.

I think that multiple PR may get open related to this issue so at the time of opening PR use `update` followed by issue number instead of `fixes` and I request reviewers not to close this issue after merging a PR as other contributors  may also open PR related to this

**Comment by Abhijay007** [comment]
I am adding solution for this error for now 

```
Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if [Gem.win](http://gem.win/)_platform?
 Auto-regeneration: enabled for 'C:/Users/abhij/Desktop/open-horizon/[open-horizon.github.io](http://open-horizon.github.io/)'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:184:in `require_relative'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:184:in `setup'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:102:in `process'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby30-x64/bin/jekyll:25:in `load'
        from C:/Ruby30-x64/bin/jekyll:25:in `<main>'
        
        ```

**Comment by joewxboy** [comment]
This should be complete
