### ISSUE TITLE
Populate get-technical-support.md

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#15]
Populate the `get-technical-support.md` file by explaining how to join the LF Edge Slack if they don't already have an account, and then posting a request in the #open-horizon-help Slack channel there.  Be sure to specify what information they should provide in order for us to help them, and provide an example.

**Comment by clementkng** [comment]
Hi @joewxboy I'm interested in taking this issue if it's still open 😄

**Comment by joewxboy** [comment]
@clementkng Edidiong has apparently been working on this one already.  As soon as he creates the PR, I'll add you as a reviewer.

**Comment by edeediong** [comment]
Hi, I'm working on this presently. Sorry @clementkng

**Comment by edeediong** [comment]
I've created the PR @joewxboy
