### ISSUE TITLE
Feature Request: Change Pages Title and Add feedback option

### ISSUE THREAD

**Issue by Sukriti-sood** [open-horizon/open-horizon.github.io#151]
### Is your feature request related to a problem? Please describe.

Most of the pages in the Open Horizon Website has title"Open Horizon". So, I want to add related title wrt. page content. Like [this](https://open-horizon.github.io/docs/getting_started/overview_oh.html) page title should "Overview- Open Horizon".

Add Feedback Option in the page as discusssed [here](https://github.com/open-horizon/open-horizon.github.io/issues/142#issuecomment-1040814356) .

**Comment by joewxboy** [comment]
Two comments:

1. Let's ensure that the name "Open Horizon is not embedded into the page.  We should instead be using variable insertion everywhere we can.  This means either the variable that is an absolute reference to the open source project, or the variable that could mean the current product, which may be a downstream distribution.  LMK if that's not clear and you need more details.
2. Let's get some feedback from @Rene-Ch1 to ensure that this change will not negatively impact downstream consumption of our documents.

**Comment by Sukriti-sood** [comment]
@joewxboy yes, this point is bit unclear to me about variable.

**Comment by Sukriti-sood** [comment]
@joewxboy Ya its clear now. Sorry for late reply.

**Comment by Sukriti-sood** [comment]
@joewxboy This issue is not completed still, that pr was one of the patch..Please reopen this.

**Comment by joewxboy** [comment]
@Sukriti-sood re-opened per your request.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood re-opened per your request.

Thanks 🙌🏻

**Comment by johnwalicki** [comment]
@joewxboy i think this issue is outdated because of the migration to the new theme?

**Comment by joewxboy** [comment]
OK, these issues are now addressed by the new theme and the updating of the front matter.  Closing.
