### ISSUE TITLE
Bug🐛: move files from /.github/workflow to /.github

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#152]
### Describe the bug.

The `config.yml` and `write-good.yml` files are in the wrong folder and need to be moved up to the parent folder.
They are currently in `/.github/workflows` and should be moved to `/.github`.

### Describe the steps to reproduce the behavior

n/a

### Expected behavior.

This move should stop error emails from being sent when PRs are merged in this repo.

### Operating environment

n/a

**Comment by Abhijay007** [comment]
@joewxboy can I work on it?
