### ISSUE TITLE
Adding workflow status badge

### ISSUE THREAD

**Issue by tushar5526** [open-horizon/open-horizon.github.io#154]
[Status Badges](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge)

We have multiple GHAs running and adding badges would make it easier for us to track failing GHAs (eg: badge for broken link checker)

**Comment by tushar5526** [comment]
Hey @joewxboy I will like to add this feature to the README.md of the repository.

**Comment by joewxboy** [comment]
@tushar5526 Can you list here which READMEs, what badges we'd display, and think about how we could also generalize this for all repos without needing to install a GHA in each (if possible).

**Comment by joewxboy** [comment]
Ahh, I see.  That's compelling.  Thanks.
