### ISSUE TITLE
Bug🐛: Fix 6 Broken Links

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#156]
### Describe the bug.

Fix the first six broken links (all 404s).  The page may exist and have been re-named, or the page may not exist.  Determine the situation and fix the link, or possibly remove the link entirely if it cannot be fixed.

For the last two, it will require modifying the GHA to enter an exception, so it's out of scope for this issue.

### Describe the steps to reproduce the behavior

1. Go to this page: https://github.com/open-horizon/open-horizon.github.io/actions/runs/1866277862
2. Click on the `Build` button
3. Click on the `>` beside "Run check for Broken Link"
4. You will see a list of 8 "broken" links.

### Operating environment

n/a

**Comment by Abhijay007** [comment]
@joewxboy can I work on it ?

**Comment by joewxboy** [comment]
Go ahead, @Abhijay007  and let me know if any of the links don't have an easy solution.
