### ISSUE TITLE
Bug🐛: Fix Check_broken_link GHA

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#157]
### Describe the bug.

There are two tasks here:

1. Two pages will need to be flagged as exceptions so that they don't show up in the report as broken links.

2. The GHA automatically files an issue if it finds broken links, but the issue template no longer exists.  Find it and restore it.

### Describe the steps to reproduce the behavior

1. Go to https://github.com/open-horizon/open-horizon.github.io/runs/5252797977?check_suite_focus=true
2. Click the `Build` button
3. Click the `>` beside "Run check for Broken Link" to see the two files at the end of the list that require exceptions
4. Look for the "Error" on line 11 in the `> Creating issue` section to see the reference to the missing issue template that needs to be restored

### Expected behavior.

When you commit your fix and create a PR, we should be able to manually run the GHA on your branch to confirm that it works.

### Operating environment

n/a

**Comment by tushar5526** [comment]
I will do it, I require the issue creation template for orphan pages checker as well

**Comment by joewxboy** [comment]
Perfect, thanks @tushar5526

**Comment by tushar5526** [comment]
Also, while I am at it. I don't think we should fail the GHA if we have some broken links. GHA should fail if we have some logical error like the one we just had.

Also, the status of broken links are displayed using an issue, so I think we should not fail the GHA if there are broken links present.

**Comment by joewxboy** [comment]
> While I am at it. I don't think we should fail the GHA if we have some broken links. GHA should fail if we have some logical error like the one we just had.
> 
> Also, the status of broken links are displayed using an issue, so I think we should fail the GHA if there are broken links present.

That makes sense.  We'll have to coordinate with the shield/badge for the orphaned page checker to see if it currently requires a fail or not.

**Comment by tushar5526** [comment]
I have a fix, would make a PR soon.

**Comment by tushar5526** [comment]
https://github.com/victoriadrake/hydra-link-checker/blob/master/hydra.py#L283

Digging more into it, the action is set to fail whenever there is a broken link present on the website.
We could fix the broken links or I have made a feature request which would rectify this problem. 

https://github.com/victoriadrake/hydra-link-checker/issues/15
