### ISSUE TITLE
Populate report-an-issue.md

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#16]
Populate the `report-an-issue.md` file with detailed on the proper way to open an issue for this project in GitHub.  At least initially, let's limit the scope to reporting an issue with the documentation.  Later on we'll expand it for reporting an issue with any code in the project.

**Comment by clementkng** [comment]
Hi @joewxboy is this issue up for grabs?

**Comment by joewxboy** [comment]
@clementkng As far as I know, it's open.  You commented first!  I'll assign to you.
