### ISSUE TITLE
Documentation📄: Update Technical Support Page

### ISSUE THREAD

**Issue by Abhijay007** [open-horizon/open-horizon.github.io#166]
### What is the current documentation state?

Update "slack" links in the technical support page as it is not redirected to anywhere and open-horizon has shifted their platform to elements for internal communication purposes.

### Where is this stated?

you can access this page from [here](https://open-horizon.github.io/common-requests/get-technical-support.html)

### Why do you want to improve the statement?

it is important links as it is required by new and existing contributors for reaching out to the community and engaging with them to ask their doubts and sharing suggestions as well. 

### Proposed Statement

Replace these links with: https://chat.lfx.linuxfoundation.org/

**Comment by Abhijay007** [comment]
@joewxboy I want to work on this one :)

**Comment by joewxboy** [comment]
@Abhijay007 Don't forget to sign-off on all your commits.

**Comment by Abhijay007** [comment]
> @Abhijay007 Don't forget to sign-off on all your commits.

sure 😅
