### ISSUE TITLE
Bug🐛: Update bundle to 2.3.7 and add to instructions

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#178]
### Describe the bug.

In the "Test your changes locally" section, update the `bundle install` code section to this:

```
gem install bundler
bundle update --bundler
bundle config set --local deployment 'true'
bundle install
bundle exec jekyll serve
```

This will ensure that you have the newest version of Bundler, the Gemfile.lock is using that newest version, and that you're using the ruby gems in e directory that you have write access to (and is the correct version of ruby for macOS users).

Please test on Windows, Linux, and macOS.

### Expected behavior.

This fixes a bundle version mis-match error, a permissions error for upgrading ruby gems, and keeps everything updated.

### Operating environment

macOS Monterey 12.2.1

**Comment by Abhijay007** [comment]
> Thanks, @Abhijay007 . Let me know if you encounter any issues running on Linux or Windows.

sure :)

**Comment by Sukriti-sood** [comment]
@Abhijay007 also working fine on Linux , I have using ubuntu.. , this [jekyll guide](https://jekyllrb.com/docs/installation/ubuntu/) is very helpful.

**Comment by Abhijay007** [comment]
> @Abhijay007 also working fine on Linux , I have using ubuntu.. , this [jekyll guide](https://jekyllrb.com/docs/installation/ubuntu/) is very helpful.

Thanks for sharing @Sukriti-sood, I am using the same guide for windows, and ya it is really helpful thanks for letting me know that it exists for Linux as well :)

**Comment by joewxboy** [comment]
> @joewxboy I tried the above commands on both `Linux` and `windows`,
> 

Thank you for testing on multiple OSes.  As we create a Makefile to support building this, we may want to consider the possibility of using two different Gemfile.lock files if they diverge too much between OSes.

**Comment by Abhijay007** [comment]
> > @joewxboy I tried the above commands on both `Linux` and `windows`,
> 
> Thank you for testing on multiple OSes. As we create a Makefile to support building this, we may want to consider the possibility of using two different Gemfile.lock files if they diverge too much between OSes.

sure, I will keep that in mind while implementing `make`
