### ISSUE TITLE
Bug🐛: exclude translations and vendor dirs from bundle serving

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#179]
### Describe the bug.

When you run `bundle exec jekyll serve`, it might pick up vendor directories and throw an error.  It will also pick up translation directories and thrown warnings.

Edit the `_config.yml` file and add the following line after the "theme:"

```
exclude: [docs/nl, vendor]
```

### Describe the steps to reproduce the behavior

Follow the standard instructions that end with "bundle exec jekyll serve" and see the warnings and errors.

Make the change to _config.yml as specified above.

Change the instructions to add "--incremental" afterwards:

`bundle exec jekyll serve --incremental`

Then run again to see errors and warnings go away.

### Expected behavior.

```
bundle exec jekyll serve --incremental
Configuration file: /Users/yournamehere/dev/open-horizon.github.io/_config.yml
            Source: /Users/yournamehere/dev/open-horizon.github.io
       Destination: /Users/yournamehere/dev/open-horizon.github.io/_site
 Incremental build: enabled
      Generating...
                    done in 4.608 seconds.
 Auto-regeneration: enabled for '/Users/yournamehere/dev/open-horizon.github.io'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
  ```

### Operating environment

macOS Monterey 12.2.1

**Comment by tushar5526** [comment]
I'll like to give it a shot. Please assign this to me.
