### ISSUE TITLE
Feature Request: Deployment preview GHA

### ISSUE THREAD

**Issue by Sukriti-sood** [open-horizon/open-horizon.github.io#183]
### Is your feature request related to a problem? Please describe.

Adding Deployment preview GHA to PRs

The addition of this feature will make it easier to review PRs.

for more info follow this discussion [here](https://github.com/open-horizon/open-horizon.github.io/discussions/198)

I would like to work on this.

**Comment by Abhijay007** [comment]
@Sukriti-sood are you planning to use netlify for this purpose?

**Comment by Sukriti-sood** [comment]
no, website is deployed on github pages, so will be creating GHA.

**Comment by Abhijay007** [comment]
cc @joewxboy

**Comment by Sukriti-sood** [comment]
First Steps of this to create Github Account , So @joewxboy If you can provide us any mail credentials or if you can create a github account youself , then It will be better kickstart for this project.

**Comment by joewxboy** [comment]
Is anyone still interested in working on this?  Let me know shorty, or I'll close it for lack of interest.

**Comment by joewxboy** [comment]
No interest, closing.
