### ISSUE TITLE
Feature Request: Implement `MakeFile` in the open-horizon docs project

### ISSUE THREAD

**Issue by Abhijay007** [open-horizon/open-horizon.github.io#189]
### Is your feature request related to a problem? Please describe.

Currently, users need to write all the commands manually in order to run the project and need to switch between the command in order to build, test and run. ,

### Describe the solution you'd like.

By implementing MakeFile in the open-horizon docs project we can define a set of tasks to be executed and run multiple commands one by one without manually writing those command, we can use alias `site` so that when the user write command `make site` then all commands that we mentioned in the file will execute one by one and serve the website on the localhost we cand do same for the other commands as well.

**Comment by joewxboy** [comment]
Just noting here that we have a discussion about this issue here: https://github.com/open-horizon/open-horizon.github.io/discussions/191
