### ISSUE TITLE
Create an issue template for this repository

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#20]
We need a basic template that specifies a simple set of required information for an issue.

First, list required fields in this issue's comments.

**Comment by rapperdinesh** [comment]
1. Issue title
2. Description
3. Reading resources 
4. Link to previous past related contributions
5. Deadline (optional)

**Comment by its-crypted** [comment]
I want to learn more about this issue. How exactly do you want this page?

**Comment by joewxboy** [comment]
@its-crypted Thanks.  The file was located in https://github.com/open-horizon/open-horizon.github.io/tree/master/.github/ISSUE_TEMPLATE

I incorporated items 3-5 suggested by @rapperdinesh
