### ISSUE TITLE
Feature Request: Install ImgBot app in open-horizon Org to squash images

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#200]
### Is your feature request related to a problem? Please describe.

Images on the Open Horizon GitHub repository are unnecessarily larger than they need to be.

Page loads are slower than optimal.

### Describe the solution you'd like.

The https://imgbot.net/ ImgBot will squash images in a repo.  This speeds page load time by reducing the image load time on unreliable or slow broadband.

An github/open-horizon Org administrator would install the ImgBot 
The ImgBot compresses the images, opens PRs that must be reviewed.

### Describe alternatives you've considered

I use pngquant from the Linux CLI but its time consuming to resize images.  Let the ImgBot do it.

### Additional context.

ImgBot is always free for open source projects.  We use it extensively in the github/IBM org.

For additional details about ImgBot - https://imgbot.net/docs/

**Comment by johnwalicki** [comment]
If other admins agree, I have sufficient github/open-horizon Org permissions to install the ImgBot app.

**Comment by joewxboy** [comment]
NOTE: This is a performance optimization and should not just be performed once.  Thus, it should also be added to a linter and applied to all new commits.

**Comment by johnwalicki** [comment]
@joewxboy and I got together and installed the ImgBot GitHub app into this Docs repo.
We will start to see ImgBot PRs against images that can be compressed.
Closing issue.
