### ISSUE TITLE
Feature Request: Replace AgBot with variable

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#204]
### Is your feature request related to a problem? Please describe.

The documentation contains many references to AgBot.  Sometimes lowercase, sometimes uppercase. This is a really a "proper name" in the documentation.  It should not be translated.  

### Describe the solution you'd like.

Replace all references of AgBot with a documentation variable.

**Comment by johnwalicki** [comment]
@joewxboy Where are the documentation variables assigned?  Is there a metatag file?
I propose we add a new variable:
```
{{site.data.keyword.agbot}}
```

**Comment by johnwalicki** [comment]
I will write a small shell program to iterate through the .md files and replace `AgBot` with the new variable.

**Comment by johnwalicki** [comment]
Once we prove how to do this, we can create separate issues / PRs for other keywords; Exchange, Secrets Manager, SwitchBoard, Content Sync Service, etc.

**Comment by johnwalicki** [comment]
@Rene-Ch1 - Please guide us here.  I believe "AgBot" should be considered a "proper noun" so that it is not translated.

Should we debate if the proper noun should be AgBot or agbot.  Whatever we choose, the documentation should be consistent (which will be easy to change if it's a variable)

**Comment by joewxboy** [comment]
> @joewxboy Where are the documentation variables assigned? Is there a metatag file? I propose we add a new variable:
> 
> ```
> {{site.data.keyword.agbot}}
> ```

https://github.com/open-horizon/open-horizon.github.io/blob/master/_data/keyword.yml

Feel free to add variables as needed following our naming convention.

**Comment by johnwalicki** [comment]
Before I make the change; the following markdown files will be modified. They contain variations of  "Agbot" "agbot" "AgBot"

```
$ find * -name "*.md" | xargs grep -i -l " agbot "
admin/accessing_logs.md
api/agbot_api.md
developing/secrets_details.md
getting_started/faq.md
hub/cluster_sizing.md
troubleshoot/index.md
user_management/security_privacy.md
using_edge_services/service_rollbacks.md
```

**Comment by johnwalicki** [comment]
We need to only substitute prose usage of AgBot.  There are some cases where agbot is part of the `hzn agbot` command.
My idea of passing this through `sed` has become more complicated.  Its a small list of affected files. I'll hand edit them.

**Comment by johnwalicki** [comment]
The documentation are a variety of prose usage of "agbots" plural.  Not certain how we should handle those cases.
```
$ find . -name "*.md" | xargs grep -i -l " agbots "
./using_edge_services/service_rollbacks.md
./user_management/rbac.md
./user_management/security_privacy.md
./installing/edge_devices.md
./installing/exchange_api.md
./installing/edge_clusters.md
./getting_started/faq.md
```

**Comment by johnwalicki** [comment]
Aha - I can write `{{site.data.keyword.agbot}}s` so that it appends the plural.

**Comment by johnwalicki** [comment]
In the branch `agbot` ,I've staged a commit with the markdown files with the {{site.data.keyword.agbot}} substitution string.

The only file that remains to be modified is `_data/keyword.yml` because I would welcome the debate around
`AgBot` versus `Agbot`

**Comment by joewxboy** [comment]
> In the branch `agbot` ,I've staged a commit with the markdown files with the {{site.data.keyword.agbot}} substitution string.
> 
> The only file that remains to be modified is `_data/keyword.yml` because I would welcome the debate around `AgBot` versus `Agbot`

@dabooz and @bmpotter and @TheMosquito any history or preference around `Agbot` versus `AgBot`?
