### ISSUE TITLE
Documentation📄: Add a doc search function/field

### ISSUE THREAD

**Issue by Rene-Ch1** [open-horizon/open-horizon.github.io#211]
### What is the current documentation state?

Add a search field that would search the entire documentation set. Here is an example from IEAM 4.3: 

![image](https://user-images.githubusercontent.com/53276773/158248718-5b2827cc-110f-44c6-b8f6-fde5842f65c9.png)

**Comment by Abhijay007** [comment]
@joewxboy I want to work on this one :)

**Comment by joewxboy** [comment]
If possible, I'd like to see if we can use an inline search tool like https://www.algolia.com/ref/docsearch/

One reason is speed and instant feedback.  Another reason is that it avoids injection attacks by not showing a page that includes search terms typed in by the visitor.  LMK if it's not clear why that's so important.

The Jekyll web site uses this type of search: https://jekyllrb.com

Do a search for `build` or `install`.  One of the nice features is that it gives feedback so quickly that you can type more slowly and see instant results with every keypress.

**Comment by Abhijay007** [comment]
> If possible, I'd like to see if we can use an inline search tool like https://www.algolia.com/ref/docsearch/
> 
> One reason is speed and instant feedback. Another reason is that it avoids injection attacks by not showing a page that includes search terms typed in by the visitor. LMK if it's not clear why that's so important.
> 
> The Jekyll web site uses this type of search: https://jekyllrb.com
> 
> Do a search for `build` or `install`. One of the nice features is that it gives feedback so quickly that you can type more slowly and see instant results with every keypress.
> 
> I also love how it groups results into sections.

I will look into this :)

**Comment by Abhijay007** [comment]
maybe CDS slove this too https://www.carbondesignsystem.com/components/search/usage/

**Comment by DivyanshuSonwal** [comment]
Hi @Abhijay007  Can I work on this issue?

**Comment by Abhijay007** [comment]
@joewxboy we can close this issue now, resolved via https://github.com/open-horizon/open-horizon.github.io/pull/376
