### ISSUE TITLE
Documentation📄: Add Table of Contents (TOC) to main doc page

### ISSUE THREAD

**Issue by Rene-Ch1** [open-horizon/open-horizon.github.io#213]
### What is the current documentation state?

Add the formatted SUMMARY file (TOC) to the main doc page view.

**Comment by joewxboy** [comment]
Let's also ensure that any product names, component names, and proper nouns are embedded using variables.

**Comment by joewxboy** [comment]
This is a good example of [a section TOC page](https://open-horizon.github.io/docs/anax/).  This would be useful for directories as a default index.  This format would probably not work for a site-wide TOC page as it would be too long.  We may want something more custom for that.

**Comment by Abhijay007** [comment]
@joewxboy I think we can close this Issue now as it is resolved with this PR : https://github.com/open-horizon/open-horizon.github.io/pull/387
