### ISSUE TITLE
Bug🐛: missing URL from _config.yml file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#214]
### Describe the bug.

WIthout adding a `url` line in the file, you cannot run tests.

### Describe the steps to reproduce the behavior

run `bundle exec jekyll doctor` and you'll get an error message about the missing configuration parameter.

### Expected behavior.

Add the following line to the /_config.yml file:

url: https://open-horizon.github.io

### Operating environment

all

**Comment by Abhijay007** [comment]
@joewxboy can I resolve this?
