### ISSUE TITLE
Documentation📄: Rasbian has become Raspberry Pi OS

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#222]
### What is the current documentation state?

The OH / IEAM documentation references `Raspbian` in several pages.  It is now called `Raspberry Pi OS`.  There are two flavors of it `32bit` and `64bit`.  This GH issue should make changes to these markdown files:

```
docs/installing/adding_devices.md
docs/getting_started/faq.md
docs/getting_started/known_issues.md
```

**Comment by sonaljain067** [comment]
@johnwalicki Can I work on this issue, in case it's still up?

**Comment by johnwalicki** [comment]
Hi @sonaljain067  - Are you planning on working on this change?

**Comment by sonaljain067** [comment]
Yeah, would do it soon!
