### ISSUE TITLE
Documentation📄: Incorporate All-in-1 Horizon Management Hub doc into the OH docs

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#224]
### What is the current documentation state?

The README over in the devops repo contains great information about how to set up the All-in-1 Horizon Management Hub, Agent, and CLI.   Those details really need to move over to the OH documentation.

This issue should track how to incorporate this page into the docs.
https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md

**Comment by johnwalicki** [comment]
There's some nice work in https://github.com/open-horizon/devops/pull/102 that should be incorporated too.

**Comment by johnwalicki** [comment]
I see that #207 recommends a GHA to copy other repo documentation into the OH docs.  We should do the same for the devops docs referenced in this ticket.

**Comment by joewxboy** [comment]
@johnwalicki This is the issue that creates the GHA in `anax` to copy their docs over:
https://github.com/open-horizon/anax/pull/3068

We need something similar in `devops` to copy their docs over, which would solve this issue.  Care to open an issue in the devops repo like PR 3068 above?

**Comment by johnwalicki** [comment]
New issue opened in the devops repo to set up a GHA.
https://github.com/open-horizon/devops/issues/106

**Comment by johnwalicki** [comment]
How that the GHA for anax/docs is implemented, let's stay on roll and also set up a GHA for devops/docs to docs/devops
https://github.com/open-horizon/anax/issues/3044

**Comment by joewxboy** [comment]
Thanks.  This work will be tracked in https://github.com/open-horizon/devops/issues/106, closing.
