### ISSUE TITLE
Documentation📄: Change container *.md file names to a index file name pattern

### ISSUE THREAD

**Issue by Rene-Ch1** [open-horizon/open-horizon.github.io#232]
### What is the current documentation state?

Change container (files that list links to other files in that section of the document) file names and others like it to and "index" naming pattern.

For example, the name for the following file name can be changed to index.md 

https://github.ibm.com/Edge-Fabric/docs/blob/4.3/developing/developing_edge_services.md

**Comment by Rene-Ch1** [comment]
Reopening and repurposing to be a generic goal.

**Comment by joewxboy** [comment]
Look in each folder to see if there isn't an index.md or index.html file.  If there isn't one, then:

1. Look at which pages exist and if one of them would make an obvious default page for that directory.  If so, rename it to index keeping the existing extension (md or html).
2. Find all pages that linked to the former filename and change those URLs.

Please ensure that all filenames are lowercase only and contain no spaces or punctuation.

**Comment by saurav1004** [comment]
Hello @joewxboy 
Can I be assigned this issue ? I would like to work on this. I have set up the documentation locally and have gotten a good understanding of the repository structure.

**Comment by joewxboy** [comment]
@saurav1004 Go ahead.  Let me know if you have any questions.

Occasionally, you may find that a directory does not have a file that can serve as an obvious index.  In that case, make a new index and list all of the documents in the folder by title and description with the title also serving as a hyperlink.  Also, make sure that the index page in the parent folder now links to the new index page in the child folder so that we are not creating an orphan page.

**Comment by johnwalicki** [comment]
Do we need to create index files now that the site has migrated to the new theme?  It might be unnecessary ?

**Comment by johnwalicki** [comment]
Also note, I have some automation that sync the OH docs with the IEAM product docs.  It compares on matching Markdown filenames.  Changing file names to index will break that.

**Comment by johnwalicki** [comment]
IMHO we should close this issue. Would like to hear other opinions.

**Comment by johnwalicki** [comment]
i do appreciate the initiative of looking through our backlog of open issues. Thanks for that!

**Comment by joewxboy** [comment]
Good point.  Thanks, @johnwalicki 

@saurav1004 I'll close this one.
