### ISSUE TITLE
Add John Walicki to MAINTAINERS.md for Docs WG and all Docs repos

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#236]
@dabooz @t-fine @naphelps @bencourliss per the expedited process we've discussed on TSC calls, I'd like to formally nominate @johnwalicki to be promoted from Contributor to Maintainer in the Documentation Worrking Group repositories.  

Maintainers are described as "Contributors who have commit access to repositories, may fill leadership roles in Working Groups, and have demonstrated positive contributions over time to further the goals of the project."

John has demonstrated both the knowledge and ability to handle the technical aspects of reviewing commits, managing tasks within the Working Group, and has shown leadership abilities in taking large changes from concept through to completion/merge.

To cement this, I'll submit a PR adding his name to the MAINTAINERS.md file in this repo, and tag you four as reviewers.  You can then give feedback as needed in the PR review process.

**Comment by johnwalicki** [comment]
Thanks!
With gratitude and readiness to serve.
-- John
