### ISSUE TITLE
Documentation📄: Support for Ubuntu 22.04 Jammy

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#238]
### What is the current documentation state?

@dlarson04 has merged support for Ubuntu 22.04  aka Jammy Jellyfish
https://github.com/open-horizon/anax/issues/3157

We should update the following docs to include `jammy`
- installing/adding_devices.md

**Comment by YashKamboj** [comment]
Hey, i would love to work on this issue

**Comment by joewxboy** [comment]
Go ahead, @YashKamboj and let @johnwalicki or @joewxboy know if you have any questions.  Feel free to respond here or in the chat room at https://chat.lfx.linuxfoundation.org/

Don't forget to sign your commits and create the PR for this with a title that begins with "Issue-238: "
