### ISSUE TITLE
typo on quick start page

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#24]
In the front matter, the description reads: "A quick start to help you familiar with Open Horizon”.

There's a word or two missing.

**Comment by morrme** [comment]
Should it be something like this: 

![qs](https://user-images.githubusercontent.com/26514778/90022275-f651db00-dc77-11ea-85aa-69b3f74d725b.png)

**Comment by joewxboy** [comment]
@morrme Sure, or even shorter:

"A guide to get you using Open Horizon in minutes"

Did you want to work on this?

**Comment by morrme** [comment]
@joewxboy yes! 🙂  PR submitted !

**Comment by mikehyde** [comment]
@morrme Please indicate that you agree to the terms of the [Developer Certificate of Origin](https://developercertificate.org/), by adding `Signed-off-by: email@address` message line to the commit. BTW, If you set your user.name and user.email as part of your git configuration, you can sign your commit automatically with git commit -s.

For your reference: 

Following LF Edge guidance for all member projects, see our single sentence on the topic: [https://wiki.lfedge.org/display/OH/Project+Contributions](https://wiki.lfedge.org/display/OH/Project+Contributions)

- Read the [Developer Certificate of Origin](https://developercertificate.org/) and sign all commits (per [Technical Charter](https://wiki.lfedge.org/display/OH/Technical+Charter), section 7.b.ii).

> 7.b.ii. All new inbound code contributionsmustalso beaccompanied by a Developer Certificate of Origin(http://developercertificate.org) sign-off in the source code system that is submitted through a TSC-approved contribution process which will bind the authorized contributor and, if not self-employed, their employer to the applicable license;
