### ISSUE TITLE
Documentation📄: summary.md has broken links

### ISSUE THREAD

**Issue by Rene-Ch1** [open-horizon/open-horizon.github.io#241]
### What is the current documentation state?

There are files that are not actually used in the built output. I discovered some of them while I was clicking on file links in the Summary.md file - some generate a 404. And Joe told me that the Summary file is not really dictate what you see in final output - and some of the files in SUMMARY don't really need to be in the repo at all.

**Comment by johnwalicki** [comment]
The summary.md is not used in the open-horizon.github.io navigation.  Do we care if there are broken 404 links?
- https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/SUMMARY.md
Would it be easier to delete summary.md that to remove / create the following broken links?

Broken Links on summary.md
- What's New - https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/getting_started/whats_new.md
- Supported Languages - https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/getting_started/languages.md
- Overview of OH - https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/getting_started/overview_ieam.md
- Air Gap - https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/installing/airgap_install.md
- Upgrade - https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/hub/upgrade.md
 - developing edge services - https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/developing/developing_edge_services.md
 -  management console - https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/console/accessing_ui.md
 - [Using the management console](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/console/accessing_ui.md)

    [Supported browsers](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/console/browsers.md)
    [Exploring the console](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/console/exploring_console.md)
 - [Using the CLI](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/cli/using_cli.md)
 - [APIs](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/api/edge_rest_apis.md)
 - [Glossary](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/getting_started/glossary.md)
[Notices](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/getting_started/notices.md)

**Comment by johnwalicki** [comment]
I suggest we delete the summary.md or do a complete rethink of the website navigation.

**Comment by johnwalicki** [comment]
Same question about dir.md
All of the links in dir.md are broken
https://github.com/open-horizon/open-horizon.github.io/blob/master/dir.md

**Comment by johnwalicki** [comment]
Who can unravel the jekyll build process for the Open Horizon GitHub pages documentation tree?

**Comment by johnwalicki** [comment]
Removing Good First Issue tag because I suspect this is an arm-wrestle with the jekyll build process

**Comment by joewxboy** [comment]
> I suggest we delete the summary.md or do a complete rethink of the website navigation.

I concur.  I also spoke with @Rene-Ch1 about this and we agree that it serves no purpose to Open Horizon.  It can safely be deleted.

**Comment by joewxboy** [comment]
> Same question about dir.md
> All of the links in dir.md are broken
> https://github.com/open-horizon/open-horizon.github.io/blob/master/dir.md

I originally created this as a way to test hyperlinks.  Now that we have link checker and orphan checker GHAs, this file is no longer needed.

**Comment by johnwalicki** [comment]
Set your blasters to vaporize.  Fire at will.
