### ISSUE TITLE
Documentation📄: RHEL edge device keyword

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#243]
### What is the current documentation state?

On the https://open-horizon.github.io/docs/installing/adding_devices.html
page, RHEL is one of the supported edge device operating systems.  However the bullet on the above html rendered page reads as:
```
8.1, 8.2, and 8.3
```
The actual .md markdown is:
```
{{site.data.keyword.rhel}} 8.1, 8.2, and 8.3
```
We need to investigate why the `{{site.data.keyword.rhel}}` keyword is not substituted correctly.

The `{{site.data.keyword.rhel}}` keyword is not defined in the `keyword.yml` file at
https://github.com/open-horizon/open-horizon.github.io/blob/master/_data/keyword.yml

Reference markdown pages:
- https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/installing/adding_devices.md

**Comment by johnwalicki** [comment]
Herre is how that page and keyword correctly renders in the IEAM product documentation:
https://www.ibm.com/docs/en/eam/4.3?topic=devices-preparing-edge-device

**Comment by johnwalicki** [comment]
The fix is to insert the following keyword in https://github.com/open-horizon/open-horizon.github.io/blob/master/_data/keyword.yml
```
  rhel:
    Red Hat Enterprise Linux&reg;
```
at the alphabetically appropriate location.

**Comment by johnwalicki** [comment]
@Rene-Ch1 @joewxboy FWIW - When comparing the IEAM product `conrefs.yml` and the Open Horizon `_data/keyword.yml` I see a variety of keyword differences (some intentional, but some omissions, some out of sync) 

Intentionally, I did not sync the keyword files in the giant #220 PR.  We should review the differences anyway?

**Comment by johnwalicki** [comment]
I noticed this missing keyword when reviewing the merged PR #242 
We should make it a practice to inspect not just the bespoke patch but the actual rendered page and the rest of the resulting document.

**Comment by johnwalicki** [comment]
The `adding_devices.md` references this `{{site.data.keyword.rhel}}` keyword in multiple places.  A complete review of 
https://open-horizon.github.io/docs/installing/adding_devices.html is recommended.

**Comment by johnwalicki** [comment]
Before merging this PR, the adding_devices.html page is missing the RHEL keyword in this sentence: 
```
While Open Horizon 4.2 supports running 8.x with Docker, it is officially unsupported by .
```

**Comment by joewxboy** [comment]
@bencourliss Do you know if Open Horizon is actually tested on RHEL?  Or is it alternatively tested on Fedora?  Or not on those OSes at all?
