### ISSUE TITLE
more best practices to document and implement

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#25]
From @Rene-Ch1 

> Some best practices comments....directional content (before, previous, after, above, and so on) are discouraged because vision impaired readers have challenges with directional content. The same goes for any visual cues like colors or descriptions of icons, shapes, arrows, and so on. Same goes for Latin-based content like i.e and etc. Slashes are also discouraged as in and/or. These things create computations for visually-impaired and translation issues. same goes for jargon or Americanisms. Just saying...:-)

* Identify and replace directional content
* Identify and replace visual cues
* Identify and replace Latin-based content (i.e. and etc, for example)
* Identify and replace "and/or" and related compound joining word/phrases
* identify and replace jargon and cultural references

Capture examples and suggested replacements and add to Style Guide.

**Comment by joewxboy** [comment]
I'll be adding these to the Wiki

**Comment by leminchan** [comment]
Hey @joewxboy, can I work on this? While working through the installation, I found that the "Copy to clipboard" button wasn't copying anything for the /use.html and /contribute.html pages (using Google Chrome). Also, I was thinking there could be an alert, saying "Copied successfully," after someone clicks it to improve clarity for users.

**Comment by joewxboy** [comment]
@leminchan Sure thing.  Let me know if you have any questions.

**Comment by rajpratyush** [comment]
@joewxboy is @leminchan working on this?

**Comment by unnati914** [comment]
Could I work on this?

**Comment by joewxboy** [comment]
Additional best practices, regarding contributing:

* Always open an issue before beginning to contribute.  No bare PRs, please.
* Try to use the appropriate issue template.  If unsure, just ask in the chat room.
* Make issues as atomic as possible.  Do not put unrelated bugs into a single issue.
* When working on an issue, follow the standard process of:
* * Forking the repo
* * Creating a local branch with the issue in the format `issue-###`
* * Commit often, each time with the `-s` or `--sign-off` flag
* * Test your committed code before creating a PR.  If unsure how to test, ask in the chat room.
* * Create the PR by prefixing the title with `Issue: ## - <title of PR less than 72 characters>`
* * Label the PR with the same labels as the issue
* * "at" mention one or more Maintainers in a PR comment, and assign it to them if you can.
* * Be prepared to answer any questions and make any changes.

**Comment by Abhijay007** [comment]
@joewxboy it will be great if we add these instructions to the contributing guide as not every newcomer or contributor is not aware of this issue here :)

**Comment by Abhijay007** [comment]
> These should be added to the documentation repo (`open-horizon.github.io`) wiki under the "Best Practices" section: https://github.com/open-horizon/open-horizon.github.io/wiki/Best-practices-for-Open-Horizon-documentation

and adding this to wiki is also pending

**Comment by joewxboy** [comment]
> > These should be added to the documentation repo (`open-horizon.github.io`) wiki under the "Best Practices" section: https://github.com/open-horizon/open-horizon.github.io/wiki/Best-practices-for-Open-Horizon-documentation
> 
> and adding this to wiki is also pending

Thanks.  You should be able to add it to the wiki by directly editing the specific page.  While you can treat the wiki like code, you don't have to.

**Comment by Abhijay007** [comment]
> > > These should be added to the documentation repo (`open-horizon.github.io`) wiki under the "Best Practices" section: https://github.com/open-horizon/open-horizon.github.io/wiki/Best-practices-for-Open-Horizon-documentation
> > 
> > 
> > and adding this to wiki is also pending
> 
> Thanks. You should be able to add it to the wiki by directly editing the specific page. While you can treat the wiki like code, you don't have to.

Thanks for letting me know this, will do that :)

**Comment by Abhijay007** [comment]
> > > These should be added to the documentation repo (`open-horizon.github.io`) wiki under the "Best Practices" section: https://github.com/open-horizon/open-horizon.github.io/wiki/Best-practices-for-Open-Horizon-documentation
> > 
> > 
> > and adding this to wiki is also pending
> 
> Thanks. You should be able to add it to the wiki by directly editing the specific page. While you can treat the wiki like code, you don't have to.

@joewxboy I think I don't have edit access for wiki, and when I cloned wiki locally to edit it and push changes I am getting an error that I don't have rights to do that (which is very obvious as pushing directly code needs specific permissions), 

I know that you mentioned not treat the wiki like code but I am not able to find any way to edit wiki other than cloning and pushing changes and later I found out that GitHub doesn't allow us to open/make PRs for the wiki? do you know any other way to edit wiki without sharing access?

**Comment by joewxboy** [comment]
@Abhijay007 OK, that's new to me.  Let me check

**Comment by joewxboy** [comment]
Confirmed that all of these items have been added to the [Best Practices wiki page](https://github.com/open-horizon/open-horizon.github.io/wiki/Best-practices-for-Open-Horizon-documentation).  Closing.
