### ISSUE TITLE
Bug🐛: Exclude files from page generation

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#253]
### Describe the bug.

Based on issue #239, exclude the following files from page generation:

* MAINTAINERS.md
* SUMMARY.md

### Describe the steps to reproduce the behavior

n/a

### Expected behavior.

Pages should not be generated on the web site based on those two markdown files.  Hopefully, nobody is linking to them.

### Operating environment

n/a

**Comment by johnwalicki** [comment]
Dont forget, we delete SUMMARY.md in #250
