### ISSUE TITLE
Documentation📄: update Docs to support Fedora 36

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#266]
### What is the current documentation state?

Modify the Documentation to support Fedora 36

The following markdown files should be updated:
```sh
$ grep -l -r -i fedora .
docs/installing/adding_devices.md
docs/getting_started/known_issues.md
```

The `_data/keyword.yml` keyword substitution file should also be updated to include `Fedora` so that it is not translated.

**Comment by johnwalicki** [comment]
This is a sub ticket for https://github.com/open-horizon/anax/issues/3257

**Comment by johnwalicki** [comment]
@joewxboy Oddly, the PR #267 associated with this ticket got merged but the Open Horizon website pages didn't get rebuild.

The page at 
https://open-horizon.github.io/docs/installing/advanced_man_install.html
does not reflect the fixes from #267

**Comment by joewxboy** [comment]
The logs for GitHub pages do not show it creating a deployment for this merge.  The trigger is merging to the master branch.  Is it possible that it wasn't merged to master?

**Comment by joewxboy** [comment]
@johnwalicki GitHub Pages is failing to generate new pages due to this error:

```
github-pages 226 | Error:  Liquid syntax error (line 22): Variable '{{site.data.keyword.Fedora}' was not properly terminated with regexp: /\}\}/
```
