### ISSUE TITLE
Service Definitions section

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#27]
From @dabooz 

> We just merged some doc on service definitions into the anax repo: https://github.com/open-horizon/anax/blob/master/doc/service_def.md It is just one piece from issue 882. I'm hoping this WG can take a look at it and figure out how to integrate it into the overall doc, then let us know what changes we should make. Once we have a pattern for this, I can fill out the rest of the doc for issue 882.

This issue is a placeholder for documenting Service Definitions.

**Comment by dcmartin** [comment]
The architecture definitions need to be explicitly listed, not referred to in some long GOLANG document.

**Comment by rajpratyush** [comment]
@joewxboy if no one is working on this Can I take it as well? @joewxboy

**Comment by unnati914** [comment]
Could I work on this @joewxboy ? if its available?

**Comment by joewxboy** [comment]
Looking at https://github.com/open-horizon/anax/blob/master/docs/service_def.md it appears to be simply describing the contents of the Service Definition file and then pointing to Examples to see what the actual files might look like.

What might be missing are answers to questions that different roles may have:
* Administrator: what fields are important to them and why?
* Developer: how should this file be created?  Who will use it?  
* Architect: will this service be a single component in a greater application, or will it be stand-alone?  What are the likely dependencies?  See this chart for an example: https://github.com/joewxboy/orra/blob/jakarta/demos/SDO-OH-EXF-dev-simple/configuration/edgex/dependency-graph.png

What might be a helpful approach is to create a blog post at https://wiki.lfedge.org/pages/viewrecentblogposts.action?key=OH similar to this one: https://wiki.lfedge.org/pages/viewpage.action?pageId=44171856 and iterate over it with a Subject Matter Expert (SME) like @dabooz and @t-fine

**Comment by joewxboy** [comment]
I believe this issue has been mostly addressed.  Let's close this ticket and if needed open a new one if there are other issues.  @johnwalicki do you concur?

**Comment by johnwalicki** [comment]
Yes, let's close this GH Issue.

There is a GitHub action which copies the anax docs into the Open Horizon documentation tree. 

This service_def page is available here:
https://open-horizon.github.io/docs/anax/service_def.html
