### ISSUE TITLE
Integrate in-place repository .md files

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#29]
Beginning with the `anax` repo, develop a way to integrate existing markdown documentation without disruption or significant refactoring.

The github-pages process allows files in `/docs` to be automatically generated into web pages and made available under the existing site at the URI pattern `/docs/[repo name]`, so for the "anax" repo, the URI would begin with `/docs/anax/`.

**Comment by rajpratyush** [comment]
@joewxboy is this issue still open for work??

**Comment by joewxboy** [comment]
@rajpratyush Thanks for asking.  I'm currently trying this approach on the anax repo with assistance from Carl G.  If we get it working right, we'll need to apply the same approach to all of the other repos.

**Comment by joewxboy** [comment]
Created issue in `anax` repo to try manually adding configuration directories: https://github.com/open-horizon/anax/issues/2667

**Comment by joewxboy** [comment]
The `anax` repo docs are working now, just not optimized:
https://open-horizon.github.io/anax/attributes.html

**Comment by joewxboy** [comment]
Issue #86 is a dependency and possible solution for this issue.

**Comment by Sukriti-sood** [comment]
@joewxboy According to me there can be two ways to integrate project repo to our docuemntation:-

- Creating jekyll website in every project and pubish it here open-horizon.github.io/project_name.
- Copying files from docs to open-horizon-github.io (which is currently implemented), but I think its not working and anaxdocscopy GHA should be used in anax repo not in this repo. And if I am missing anything in between,please correct me.

**Comment by joewxboy** [comment]
@Sukriti-sood Yes, you've nailed it!

Our original approach was to create /docs GitHub Pages in each repo that would be served as a subdirectory of the main web site.  However, that turned out to not be a viable option since the web site configuration files (config.yml, _data, and so on) would have to be duplicated in each repo and maintained individually.  This approach is not scalable when you have 60+ repos in the project.

Our current approach is to create a GHA that looks for commits that contain changes to files in `reponamehere/docs` in a repo and then copying the files to the mapped folder in `open-horizon.github.io/reponamehere`.  As you noticed, the GHA that was built and deployed watches the documentation repo for updates to /docs (not the target repo) and then copies files from /docs (not the target repo) to the exact same location.  

After looking at the currently-implemented solution it appears that the code will do what we want it to do, and fixing it should merely be a configuration update.  What I do not know yet is if the GHA needs to be moved to the source repo, and if the GHA can be extended to cover all of the source repos, or if we need a copy in each source repo.

**Comment by Sukriti-sood** [comment]
@joewxboy Current GHA is using [copycat-action](https://github.com/andstor/copycat-action) which is used to copy files from the ```repository``` running workflow to other `repository`. So we need to copy this GHA in every `repo`. I want to do more search in this regard, it would be better if we can find more better way.

**Comment by Sukriti-sood** [comment]
@joewxboy I did some search but I didn't found any other approach still.

According to me setting up project docs with jekyll website, will also go well, We can set up template for docs and that can be used in every project.  Also [jekyll](https://github.com/jekyll) is also using same approach for its doc.

Or we can also pratically ananlys performance first by implementing jekyll website in one project and GHA in other.

What your thoughts?

**Comment by joewxboy** [comment]
@Sukriti-sood Yes, let's get an issue filed in `anax` repo to add the "anaxcopydocs" GHA and configure it to copy over to `open-horizon.github.io/docs/anax`.  Once we've confirmed that this works properly, we'll open issues to replicate in other repos.

**Comment by joewxboy** [comment]
Closing due to anax copy docs GHA and will open individual issues in each repo as needed.
