### ISSUE TITLE
Documentation📄: Add page/section for edge cluster setup and installation

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#293]
### What is the current documentation state?

The current section of the docs website is three pages beginning at https://open-horizon.github.io/docs/installing/edge_clusters.html

New content has been created [in the wiki](https://wiki.lfedge.org/display/OH/How+to+Set-up+and+Install+an+Edge+Cluster+Agent) and support has been added for several new Kube cluster distributions.

Let's evaluate the existing content and determine how to integrate the new wiki content.  One particular decision is if we'll have a separate page for each Kube distro, or use a single page and hide any content not relevant to the selected distro (or just show all of them inline).

### Where is this stated?

The current section of the docs website is three pages beginning at https://open-horizon.github.io/docs/installing/edge_clusters.html

### Why do you want to improve the statement?

The current instructions are incomplete, slightly broken, and do not cover all supported Kubernetes distributions.

### Proposed Statement

See the new wiki pages: https://wiki.lfedge.org/display/OH/How+to+Set-up+and+Install+an+Edge+Cluster+Agent

**Comment by joewxboy** [comment]
@johnwalicki and @Rene-Ch1 let's discuss at the next Docs WG meeting.

**Comment by johnwalicki** [comment]
Next OH Docs WG meeting is tomorrow (Tuesday 7/12) I have a conflict and can't attend the WG call.

We already have a ticket open for a Edge cluster agent install refresh.  See:
https://github.com/open-horizon/open-horizon.github.io/issues/282
Suggest we close this issue and pile on in #282.
