### ISSUE TITLE
Feature Request: Create a GitHub Action to incorporate KubeArmor-Integration docs

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#304]
### Is your feature request related to a problem? Please describe.

The https://github.com/open-horizon/kubearmor-integration repo will soon have a `/docs` directory.
We should implement a GitHub Action to copy the kubearmor-integration documentation tree into the Open Horizon Documentation site.

### Describe the solution you'd like.

Similar to GitHub Actions that copy over anax and devops documentation into the Docs tree, there should be a kubearmor-integration GHA.

### Additional context.

See example GHA in

- https://github.com/open-horizon/devops/tree/master/.github/workflows
- https://github.com/open-horizon/anax/tree/master/.github/workflows

We may want to transfer this issue into the https://github.com/open-horizon/kubearmor-integration issues list?

**Comment by johnwalicki** [comment]
FYI - @nyrahul  @Ankurk99

**Comment by joewxboy** [comment]
@johnwalicki Created this PR: https://github.com/open-horizon/kubearmor-integration/pull/6

**Comment by johnwalicki** [comment]
Thanks @joewxboy  - I've merged https://github.com/open-horizon/kubearmor-integration/pull/6
If @Ankurk99 wants to submit a PR that touches the README.md, the GHA will run and we can observe the results.

**Comment by johnwalicki** [comment]
Completed.
