### ISSUE TITLE
Documentation📄: Consistent index.html Card Titles

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#318]
### What is the current documentation state?

The https://open-horizon.github.io/docs/index.html has several cards with different titles that are not consistent.
Rene suggested we use Active Voice - "Administering", "Installing", "Integrating" for card titles.
- Change the "Installation" card to "Installing"

Steps:
- Edit this file: https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/index.html
- Make the changes suggested above.

Once the PR is merged, we can test / review the update by visiting:
- https://open-horizon.github.io/docs/anax/index.html

**Comment by BikeMouse** [comment]
Hey! I would like to contribute to this, is it possible I could get assigned to this issue?

**Comment by johnwalicki** [comment]
Thanks @BikeMouse !

**Comment by joewxboy** [comment]
@BikeMouse Let us know if you run into any issues.  Pardon me if you already know this, but please ensure that all commits are signed-off, and when creating a PR, title it in the pattern "Issue-###: [Issue title]".

**Comment by BikeMouse** [comment]
Changes made accordingly to above instructions
