### ISSUE TITLE
Feature Request: Installation Guide for setting up LFEdge hosted Mgmt Hub

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#324]
### Is your feature request related to a problem? Please describe.

There is an Installation Guide for setting up an LFEdge hosted Open Horizon Mgmt Hub. See
[doc](https://wiki.lfedge.org/display/LE/Open+Horizon+Management+Hub+Developer+Instance)

Its hidden in the LFEdge Wiki.  It should move into the Open Horizon Docs repo.

This issue needs help to reformat the wiki page into markdown.

The new markdown file should be created in 
https://github.com/open-horizon/open-horizon.github.io/tree/master/docs/hub

Let's name this file  `lfedge_mgmt_hub.md`

**Comment by johnwalicki** [comment]
Once the page is created, we'll want to link to it from 
https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/hub/hub.md

**Comment by dipesh-rawat** [comment]
Hey @johnwalicki I would like to have a go at this. Could you please assign this issue to me?

**Comment by joewxboy** [comment]
@dipesh-rawat I also have some notes to add.

Keep in mind that there are at least two different personas or use cases:

1. Developer looking to get an account added to the server
2. Administrator looking to add a developer to the server
