### ISSUE TITLE
Feature Request: Add a Link to the OH YouTube Playlist

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#325]
### Is your feature request related to a problem? Please describe.

Add a [Open-Horizon Video playlist](https://www.youtube.com/playlist?list=PLgohd895XSUddtseFy4HxCqTqqlYfW8Ix) on YouTube link to the "Learning" card.

The top level Open Horizon index.html is here:
https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/index.html
The rendered page is 
https://open-horizon.github.io/docs/

The Learning card should have another bullet.
"Open Horizon Video playlist"

**Comment by johnwalicki** [comment]
New Contributors, please read the [CONTRIBUTING](https://github.com/open-horizon/.github/blob/master/CONTRIBUTING.md) file before asking that this issue be assigned to you. Do not submit a PR for this issue without it being assigned to you.

**Comment by Mustafa-Azad025** [comment]
hey @johnwalicki ,
this mean i have add a link of playlist in learning section

**Comment by johnwalicki** [comment]
@Mustafa-Azad025 Yes, this Issue and PR will track the addition of a Playlist link to the index.html

**Comment by joneskj55** [comment]
Hey @johnwalicki, I'll take this if no one is assigned.

**Comment by johnwalicki** [comment]
@joneskj55 I've assigned this GH issue to you. Thanks!

Don't forget to sign your commit. (Explained in the CONTRIBUTING.md)

**Comment by johnwalicki** [comment]
@joneskj55  Well done - Thanks for contributing to Open Horizon
Closed by #326
