### ISSUE TITLE
Feature Request: OH Docs website redesign - adopt a MkDocs theme

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#329]
### Is your feature request related to a problem? Please describe.

The OH Documentation website needs a refresh.  Navigation is suboptimal. We've had to tweak the responsive design of the page css to adapt to screen layouts.

### Describe the solution you'd like.

We have made attempts in the past but have been blocked by the substantial rewrite of all the documentation pages.

### Describe alternatives you've considered

We should consider adopting a MkDocs Theme.  It would be a minimal impact to the documentation markdown.  There are many choices to choose from. See https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes

Is there a MkDocs theme for Carbon Design System? 
https://github.com/carbon-design-system/carbon/discussions/11814

### Additional context.

This is more complex than a Good First Issue.  Potentially a good RCOS semester long project?

**Comment by johnwalicki** [comment]
@joewxboy  suggested that we want to find a GitHub Pages theme, not a MkDocs theme.

So - let's ditch the MkDocs theme idea.

I found this "Skylight Jekyll Theme - based on Carbon Design System"  Its mostly in Korean so hard to determine if it fits our needs.
https://github.com/lego37yoon/skylight-jekyll-theme

The website example is at https://skylight.paperbox.moe/

Might be worth an experiment if someone with GitHub / web design skills wants to see what the OH Docs site looks like with this Skylight theme.

**Comment by joewxboy** [comment]
I'll try this theme to start: https://jekyllthemes.io/theme/just-the-docs

**Comment by Abhijay007** [comment]
> I'll try this theme to start: https://jekyllthemes.io/theme/just-the-docs

@joewxboy Let me know if you need any assistance regarding the same, I am excited for the docs site re-design as we are thinking about the same for a long time now.
