### ISSUE TITLE
Bug🐛: Page Description field does not interpolate variables

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#331]
### Describe the bug.

See the page description at https://open-horizon.github.io/docs/api/agent_api.html

```
Agent APIs are REST APIs for the {{site.data.keyword.horizon}} agent running on an edge node.
```

The variable key/directive should not be visible.

### Operating environment

n/a

**Comment by johnwalicki** [comment]
Opps - I also opened this issue about the same topic.  See #332

**Comment by dipesh-rawat** [comment]
@joewxboy @johnwalicki Could you please assign this issue to me for the fix?

**Comment by dipesh-rawat** [comment]
From my searching around for the fix, I found issue on Jekyll repo (https://github.com/jekyll/jekyll/issues/6815) which is highlights core jekyll lacks the functionality of string interpolation in YAML frontmatter.
