### ISSUE TITLE
Bug🐛:  Hyperlink format is incorrect on All-in-One doc

### ISSUE THREAD

**Issue by marhabac33** [open-horizon/open-horizon.github.io#338]
### Describe the bug.

Hyperlink format is `HTML` therefore it shows up as plain text instead of hyperlink
on https://open-horizon.github.io/docs/mgmt-hub/docs/index.html

### Describe the steps to reproduce the behavior

It is an content issue not an behavioural  
1. Go to https://open-horizon.github.io/docs/mgmt-hub/docs/index.html
2. Scroll to `System Requirements`

### Expected behavior.

Should be a click-able hyper link

### Screenshots.

[![Screen Shot 2022-10-11 at 11 30 49 PM](https://user-images.githubusercontent.com/8888996/195243534-4bca1ab4-e7e2-4700-9c25-b7e76ade26e3.png)](https://open-horizon.github.io/docs/mgmt-hub/docs/index.html)

### Operating environment

All

**Comment by marhabac33** [comment]
@joewxboy can I work on this issue?

**Comment by joewxboy** [comment]
@marhabac33 It has now been assigned to you.  Enjoy!
