### ISSUE TITLE
Documentation📄: Update link from GH to docs web site

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#340]
### What is the current documentation state?

In the page at https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/developing/developing_details.md it points to `service_def.md` with an absolute URL.  This means that a person browsing the documentation web site generated from GitHub will follow that link taking them from the web site to GitHub.  And yet that page also exists in the web site.  Please update the URL to point to the version of the page in the web site: https://open-horizon.github.io/docs/anax/docs/service_def.html

The direct link to GitHub.com occurs three times in `developing_details.md`.

**Comment by mnkyjs** [comment]
@joewxboy can yopu please assign me 😊

**Comment by johnwalicki** [comment]
The proper way to resolve this would be to use relative links.  Someone viewing the pages in GitHub, would stay in the github repo. Someone viewing the page from the website would stay on the website.

**Comment by joewxboy** [comment]
> The proper way to resolve this would be to use relative links. Someone viewing the pages in GitHub, would stay in the github repo. Someone viewing the page from the website would stay on the website.

Ideally, but that would only be possible if the paths were the same.  I don't believe they are in this case.

**Comment by johnwalicki** [comment]
Right.  Hmm.  Linking between multiple repositories and the website is not optimal.

**Comment by johnwalicki** [comment]
Closed by #341
