### ISSUE TITLE
Documentation📄: Add a new common issue for deploy-mgmt-hub.sh to the list

### ISSUE THREAD

**Issue by marhabac33** [open-horizon/open-horizon.github.io#346]
### What is the current documentation state?

When running the `deploy-mgmt-hub.sh` script there is a common issue with `Mongo version` that can occur and the script can fail

this is currently not included in the list of common issue on  [troubleshoot page](https://open-horizon.github.io/docs/troubleshoot/) 

### Where is this stated?

https://open-horizon.github.io/docs/troubleshoot/

### Why do you want to improve the statement?

- Since anyone encountering the issue will refer to troubleshoot page for solution
- It is a common issues

### Proposed Statement

Include new new issue with details about the error and how to resolve it.

**Comment by joewxboy** [comment]
The way you can tell if the source is in this repo or another is by the URL path.  We try to use the repo name under docs if the content is sourced from there.  For example, if a doc is in `anax/docs` the URI will be `/docs/anax/docs`.  Likewise devops/docs can be found in `/docs/devops/docs`.  Those may be the only two repos that we've added the automation for so far.

**Comment by johnwalicki** [comment]
Would be good to add this tip to https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/troubleshoot/troubleshooting.md

**Comment by marhabac33** [comment]
@johnwalicki I can open a new issue to add the tip.
