### ISSUE TITLE
Documentation📄: Add a tip about which open-horizon.github.io docs synced

### ISSUE THREAD

**Issue by marhabac33** [open-horizon/open-horizon.github.io#348]
### What is the current documentation state?

No Information about which docs in [open-horizon.github.io/docs](https://github.com/open-horizon/open-horizon.github.io/tree/master/docs ) is synced using another repo docs

### Where is this stated?

Not stated anywhere

Need to add it on 
https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/troubleshoot/index.md or 
https://github.com/open-horizon/open-horizon.github.io/blob/master/README.md

### Why do you want to improve the statement?

- it will help new contributors understand how https://github.com/open-horizon/open-horizon.github.io/ operators
- it will prevent duplicate PR(s)
- it will prevent content from getting overwritten

### Proposed Statement

Some docs under [open-horizon.github.io/docs](https://github.com/open-horizon/open-horizon.github.io/tree/master/docs) can have its source in different repo.

The way you can tell if the source is in this repo or another is by the URL path. If the source is in different repo then sourced repo name is used under docs. 

For example, if a doc is in `anax/docs` the URI will be ` /docs/anax/docs`. It is sourced from `anax` repo (i.e https://github.com/open-horizon/anax/tree/master/docs) 
Likewise `devops/docs` can be found in `/docs/mgmt-hub/docs`. (i.e https://github.com/open-horizon/mgmt-hub/tree/master/docs) 

Any changes to docs sourced from another repo should made in corresponding repo. 

`CopyDocs GitHub Action` which will trigger on a PR merge and the file will be copied over to the `open-horizon.github.io` repo.

**Comment by marhabac33** [comment]
@johnwalicki any comments on whether is better to add this tip on troubleshoot page or README page? Thanks

**Comment by joewxboy** [comment]
@marhabac33 Yes, please add to both.  It would be good to have it on troubleshooting for those trying to fix a problem based on this issue.  It is also helpful to have this on the initial documentation repo's README as a note to developers.

**Comment by marhabac33** [comment]
@joewxboy please assign it to me. I have a PR open soon. Thanks

**Comment by joewxboy** [comment]
@marhabac33 Thanks for being willing to take on this issue.  Do you have time to work on it now, or should I un-assign you to open it up for someone else to work on?

**Comment by marhabac33** [comment]
@joewxboy sorry my apologies, this slipped my mind. Please allow me couple more days. I have the changes ready somewhere just need to push a PR. once again extremely sorry
