### ISSUE TITLE
Documentation📄: Add "supported devices" to Installing box on Docs index

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#352]
### What is the current documentation state?

There is currently no clear link to supported devices, and it's not obvious how to find the information.  Let's surface it on the Docs index page (Docs link in top menu nav bar) in the "Installing" box:

https://open-horizon.github.io/docs/installing/adding_devices.html

**Comment by joewxboy** [comment]
Remember to build and test locally before committing.

**Comment by johnwalicki** [comment]
@joewxboy  Over in #359 and PR #362 I am making changes to the index.html page.
I can roll in this update as well.

**Comment by johnwalicki** [comment]
https://github.com/open-horizon/open-horizon.github.io/pull/362/commits/84970b8cdd5bc26104ed43504dcc514e322f9a15

**Comment by johnwalicki** [comment]
The #352 PR has been merged and includes this suggestion.  Closing ticket as complete.
