### ISSUE TITLE
Determine the fate of Software Defined Radio example documentation

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#358]
The [SDR example](https://github.com/open-horizon/examples/tree/master/edge/services/sdr) has [depreciated](https://github.com/open-horizon/examples/pull/550) the cloud functions components.  This caused several broken links in the OH Docs ( See #350 )
I opened a PR ( #357 ) to remove the SDR Cloud links and sections.

The remaining [SDR example documentation page](https://open-horizon.github.io/docs/installing/software_defined_radio_ex.html) is somewhat half useful.  We should decide on the fate of this page...

I see two possible paths forward:
- Sunset the [docs markdown](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/installing/software_defined_radio_ex.md) and move some of the remaining readme markdown pieces over to the SDR examples directory (linked above)
- Improve the SDR doc to showcase what you can do with Event Streams (or convert to MQTT and subscribe a Node-RED flow to it)

**Comment by johnwalicki** [comment]
The OH Docs does not highlight many / any other OH Examples.  Why was this specific example documented?

One could argue that we should sunset the OH Docs [software_defined_radio_ex.md](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/installing/software_defined_radio_ex.md) page and move the docs over to SDR example repo/directory.

**Comment by t-fine** [comment]
Sunset the [docs markdown](https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/installing/software_defined_radio_ex.md) and move some of the remaining readme markdown pieces over to the SDR examples directory 

Second action team ... LINK to new open-horizon-services hello word distributed application

**Comment by johnwalicki** [comment]
We can also move the SVG image to the examples SDR repo and delete it from the OH Docs repo.
```
https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/images/edge/08_sdrarch.svg
```

**Comment by johnwalicki** [comment]
@t-fine - Can you review this issue? I think the final step is to :

- In the Docs repo, delete the `https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/images/edge/08_sdrarch.svg`

**Comment by johnwalicki** [comment]
We need to confirm with @Rene-Ch1  that the 08_sdrarch.svg is NOT used by this downstream document:
https://www.ibm.com/docs/en/eam/4.4?topic=examples-software-defined-radio-edge-processing
