### ISSUE TITLE
Documentation📄: Change theme color and add logo

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#381]
### What is the current documentation state?

Currently a lavender color, change to Open Horizon blue.

Add logo in nav bar, preferably the favicon.

**Comment by dipesh-rawat** [comment]
Hey @joewxboy I would like to have a go at this issue. Could you please assign this issue to me?
(cc: @johnwalicki)

**Comment by dipesh-rawat** [comment]
I have attempted to implement the neccessary changes and created a draft PR https://github.com/open-horizon/open-horizon.github.io/pull/382 with changes. If you could please review the same and let me know if anything is missing.

**Comment by johnwalicki** [comment]
Looks great!

**Comment by johnwalicki** [comment]
It looks fine on Chrome but on Firefox (Linux and Mac) the "Search Open Horizon" no longer appears in the main-header. The Home / Quick Start / ... are smashed to the right.  There's something wrong with `<div class=search>`

Aha! the `picture` div above it (which changed in this PR) has some invalid html.  There's an extra "

<img src="/img/logos/open-horizon.png" "="" style="height: 90%; max-width: auto; padding-top: 5px;">

**Comment by johnwalicki** [comment]
![image](https://user-images.githubusercontent.com/17571232/215287976-9e39d83a-9e35-4ffc-8e8f-a1df2634df96.png)

**Comment by johnwalicki** [comment]
I fixed this in https://github.com/open-horizon/open-horizon.github.io/pull/384
