### ISSUE TITLE
Feature Request: OH Docs web site - Table of Contents navigation structure

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#386]
### Is your feature request related to a problem? Please describe.

The migration of the https://open-horizon.github.io is looking great.
We need to organize the Table of Contents navigation structure using the "Just the Docs" nav parameters.

Details on how to customize the navigation is posted here:
https://just-the-docs.github.io/just-the-docs/docs/navigation-structure/

We need to map out the structure and add directives to the content pages.

**Comment by dipesh-rawat** [comment]
Hi @johnwalicki I would like to have work on this issue. Could you please assign this issue to me?
Also, could you raise similar issue in anax repo as few doc files are copied from there and will need changes there.

**Comment by johnwalicki** [comment]
@dipesh-rawat  Thanks - I've assigned this issue to you.  Will review your PR.

I'm doing other work in the Anax docs.  Will tag those pages into a hierarchy.
