### ISSUE TITLE
Create folder for contributed markdown documentation

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#40]
Create a folder named `docs` and place generated markdown files in it so that Jekyll (github-pages) can automatically generate the documentation.

**Comment by its-crypted** [comment]
Should the *.md file be shifted from common-requests to docs?

**Comment by edeediong** [comment]
Can you sign this to me please? @joewxboy

**Comment by rajpratyush** [comment]
@joewxboy does this issue still needs work?
