### ISSUE TITLE
Link to YouTube playlist

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#41]
LF Edge maintains a YouTube playlist of videos about the Open Horizon project.  The documentation web site should have a convenient and obvious pointer to that playlist for anyone who may need it.

https://www.youtube.com/playlist?list=PLgohd895XSUddtseFy4HxCqTqqlYfW8Ix

h/t @TheMosquito

**Comment by chinmaym07** [comment]
Hey @joewxboy Can I work on this issue .?

**Comment by joewxboy** [comment]
@chinmaym07 Go ahead.  I'll assign it to you.

What did you have in mind?

**Comment by chinmaym07** [comment]
I am thinking to place a link to the Youtube playlist under Learn More Section as it is empty . Can you please provide your inputs on this @joewxboy .
![Screenshot_2021-02-02 Quick Start](https://user-images.githubusercontent.com/44670961/106616047-1a410a00-6593-11eb-8f74-5b6fc68b94b4.png)

**Comment by joewxboy** [comment]
Excellent!  That's a good place for it.  Go ahead, and let me know if you have any other placement ideas as well.
