### ISSUE TITLE
Bug🐛: redundant directives

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#419]
### Describe the bug.

in `./docs/installing/adding_devices.md` there are two links at the very bottom of the file that have redundant directives in at least two links.  Please remove the redundant directives.

```
{:target="_blank"}{: .externalLink}{:target="_blank"}{: .externalLink}
```

It should be:

```
{:target="_blank"}{: .externalLink}
```

### Operating environment

All

**Comment by johnwalicki** [comment]
Good catch @joewxboy 
Will push a fix
Do we have issue to restore the External Link icon ?
I think we lost that when we moved to the new design.
