### ISSUE TITLE
Suggestions to improve contribution section

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#42]
From @bmpotter 

```
Could you make a few additions to https://open-horizon.github.io/common-requests/contribute.html :

- Point out the LF Edge slack work space as another option for discussing an issue
- How can they get an issue assigned to them? (I forget, do we have to add them as a member of open-horizon before we can assign an issue to them?)
- Testing requirements for submissions: a PR must pass the automated tests or you need to update the PR until it does. In the (relatively small) cases where code isn’t covered by e2edev they need to describe in the PR the testing they did on their submitted code
- Should we say something about who to request to review a PR? When PRs just show up, they sometimes aren’t noticed right away, because there is a lot of activity (especially in anax)
- 
```

**Comment by chinmaym07** [comment]
Hey @joewxboy Can I work on this issue .?

**Comment by diru1100** [comment]
I would like to work on this issue @joewxboy. It would be a good way to get started with OH.

**Comment by joewxboy** [comment]
@chinmaym07 Did you want to see if you could collaborate on this with @diru1100 ?

**Comment by chinmaym07** [comment]
@joewxboy as @diru1100  is wanting to work on this issue . Let him do this ...I'll work on some other issue. Thankyou . :+1: 😀

**Comment by joewxboy** [comment]
OK @diru1100 , make us proud! :). Feel free to ask questions and comment as you go along.  The basic instructions in the README for the repo will let you know how to preview locally.  Please test locally in Chrome, Firefox, and a mobile browser (or simulated mobile browser) before creating a PR.

**Comment by diru1100** [comment]
https://user-images.githubusercontent.com/39561007/107151734-1eea3180-698a-11eb-9603-700f84b4f89c.mov

I took some liberty to make modifications additional to what this issue specifies. Let me know if this is ok.
- I changed the subheadings and added a description to the page.
- How to get assigned is already present, don't know if additional details are required.
- Can also give a list to working groups page to contact people who are responsible for respective projects. (I kept this under discuss)

**Comment by joewxboy** [comment]
Thanks, @diru1100

Good job seeing the missing sub-heading & description and adding those.

I'd hate to add contact info to this page, just to have to keep it updated whenever it changes.  How about providing links to the Working Groups in the wiki per repository?  That is less likely to change, and the wiki pages do get updated.  For example, to request a review in the following repositories, select the Maintainer from the related Working Group:
(example) 
[anax](https://github.com/open-horizon/anax) repo - [Agent](https://wiki.lfedge.org/display/OH/Agent+Working+Group)  Working Group
[exchange-api](https://github.com/open-horizon/exchange-api) repo - [Management Hub](https://wiki.lfedge.org/display/OH/Management+Hub+Working+Group) Working Group
[open-horizon.github.io](https://github.com/open-horizon/open-horizon.github.io) repo - [Documentation](https://wiki.lfedge.org/display/OH/Documentation+Working+Group) Working Group

**Comment by diru1100** [comment]
@joewxboy 
I have edited again and kept the links you mentioned. Kindly check it out and if it's good I will make a PR. 

https://user-images.githubusercontent.com/39561007/107371969-e6be2c80-6b0a-11eb-8488-b0ce85096a17.mov

**Comment by joewxboy** [comment]
@diru1100 Great!  Ready to submit a PR with the updates?

**Comment by joewxboy** [comment]
Make sure you sign off on the commits, and link the PR to this issue.
