### ISSUE TITLE
Feature Request: restore External Link directive

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#434]
### Is your feature request related to a problem? Please describe.

The `{:target="_blank"}{: .externalLink}` directives previously added an arrow icon/emoji  that indicated that the link would launch a new tab to an external website (and leave the OH documentation).

The OH docs have hundreds of these directives sprinkled throughout the Markdown pages.

This feature was lost / dropped during one of the theme migrations.

Can we bring it back?

**Comment by johnwalicki** [comment]
Thanks for bringing back the launch glyphs. The pages are looking great. 🔥

**Comment by joewxboy** [comment]
LMK if you want the ones in the side nav to match

**Comment by johnwalicki** [comment]
Actually I like the glyph in the Nav bar better.

**Comment by joewxboy** [comment]
OK, that one's white.  I'll see if it takes on the color of the surrounding theme context.  If so, we can swap out the other and use this everywhere.  I'll open a separate ticket for that.  Thanks, @johnwalicki
