### ISSUE TITLE
Bug🐛: page not in the navigation

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#437]
### Describe the bug.

This page is not in the OH Docs navigation

- https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/developing/transform_image.md

We should think which section it belongs.

### Operating environment

all

**Comment by joewxboy** [comment]
I'd add it to the bottom of this page: https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/developing/developingstart_example.md

And of course to the index.md

**Comment by johnwalicki** [comment]
@Rene-Ch1 has that page within the /developing/ subtree section.
See navigation sidebar at
https://www.ibm.com/docs/en/eam/4.4?topic=devices-transform-image-edge-service

Possibly make the parent this page:
https://open-horizon.github.io/docs/developing/
