### ISSUE TITLE
Bug🐛: Broken links in developing/developing_details.md

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#446]
### Describe the bug.

There are several broken links in `developing/developing_details.md`

The "Service Definition" links are broken.
I also see several lint issues.

### Operating environment

all

**Comment by johnwalicki** [comment]
Also - the SVG image does not appear on this page.

**Comment by joewxboy** [comment]
It looks like the image fix can keep the inline styles, if you wish:

![Services in a pattern](../images/edge/07_What_is_an_edge_node.svg){: style="margin: 3%"}
