### ISSUE TITLE
Bug🐛: missing externalLink directives

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#450]
### Describe the bug.

There are many dozens of markdown pages in this repo that are not correctly using the `{:target="_blank"}{: .externalLink}` directive.

The below unix pipeline finds `https://` links in the markdown files that DO NOT have the externalLink directive. (I try to exclude false positives with the `-v` option, but don't filter all of the false positives)
 
```
git clone git@github.com:open-horizon/open-horizon.github.io.git
cd open-horizon.github.io/docs

find . | grep md | xargs grep -r https | grep -v "externalLink\|url\|export\|wget\|bluehorizon\|oc login\|api\|apt" | cut -d: -f1 | sort | uniq
```

Here are the markdown files that I think need to corrected:
```
./admin/backup_recovery.md
./admin/multi_tenancy.md
./anax/docs/all-in-1-setup.md
./anax/docs/attributes.md
./cli/cloudctl_oc_cli.md
./developing/best_practices.md
./developing/container_registry.md
./developing/developing_secrets.md
./developing/examples.md
./developing/model_management_details.md
./developing/secrets_details.md
./developing/service_containers.md
./fdo/README-FDO1.1.md
./getting_started/known_issues.md
./hub/lfedge_mgmt_hub.md
./installing/advanced_man_install.md
./installing/edge_cluster_agent.md
./installing/preparing_edge_cluster.md
./kubearmor-integration/docs/README.md
./mgmt-hub/docs/index.md
./user_management/security_privacy.md
./using_edge_services/cpu_load_example.md
```

### Operating environment

all

**Comment by johnwalicki** [comment]
Don't forget when inserting the `{:target="_blank"}{: .externalLink}` directive to also add a single blank whitespace inside the `[linked text ]`.  This will put a little bit of space between the word and the launch glyph icon. 

aka `[Docker ](https://docker.io){:target="_blank"}{: .externalLink}`

**Comment by johnwalicki** [comment]
Also remember to update the `lastupdated: "2023-02-24"` front matter date on the top of the file (with the date when you touch the file)

**Comment by joewxboy** [comment]
THanks.  I've added those tips to the [Best Practices wiki page](https://github.com/open-horizon/open-horizon.github.io/wiki/Best-practices-for-Open-Horizon-documentation)

**Comment by dipesh-rawat** [comment]
@johnwalicki I can look into providing fix for this issue. Could you please assign this to me.

**Comment by dipesh-rawat** [comment]
@johnwalicki I have created a draft PR #455 with the required changes. If you could please review the same and let me know if its looks good.

**Comment by johnwalicki** [comment]
This was good, but there are some more fixes required.  Reopening.

**Comment by johnwalicki** [comment]
The entire  /common_requests/ tree is not part of the documentation website and should have been skipped.  We might need to revert those edits.  Those files were not included in my initial issue comment.  ONLY the docs/ tree should have been modified.

**Comment by johnwalicki** [comment]
I have reviewed the following pages:

-    https://open-horizon.github.io/docs/cli/cloudctl_oc_cli/
-    https://open-horizon.github.io/docs/developing/cicd_process/
-    https://open-horizon.github.io/docs/developing/container_deployment_options/
-    https://open-horizon.github.io/docs/developing/developing_details/
-    https://open-horizon.github.io/docs/getting_started/developer_learning_path/
-    https://open-horizon.github.io/docs/installing/fdo/
-    https://open-horizon.github.io/docs/installing/sdo/
-    https://open-horizon.github.io/docs/integrating_index/
-    https://open-horizon.github.io/docs/using_edge_services/cpu_load_example/

The following pages still have problems:
- https://open-horizon.github.io/docs/developing/container_deployment_options/ (broken link)
- https://open-horizon.github.io/docs/installing/fdo/  (missing a spacer between link and glyph)
- https://open-horizon.github.io/docs/integrating_index/ (broken link)
-
