### ISSUE TITLE
Bug🐛: Convert the custom class rule for external links to use alternate glyph

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#456]
### Describe the bug.

Per @johnwalicki and good taste, the glyph used in the primary nav bar for external links is simpler, better looking, and easier to understand.  Replace the rule that uses the current glyph with the alternate.

### Operating environment

All

**Comment by johnwalicki** [comment]
The nav glyph is white.  Is there a inverse, black glyph,  that can be used on the documentation pages?

We could even set up a light/dark theme for the glyph?

Possibly someone with design/graphics skills could assist?

**Comment by johnwalicki** [comment]
The new glyph looks great !
