### ISSUE TITLE
Bug🐛: Delete /faq/index.html and /_posts/*

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#459]
### Describe the bug.

I propose we delete the outdated FAQ html page: https://open-horizon.github.io/faq/

See https://github.com/open-horizon/open-horizon.github.io/blob/master/faq/index.html

Also delete the sources files this FAQ uses  :
```
_posts/2020-08-18-restart-agent.md
_posts/2020-08-19-sample-faq.md
_posts/2020-08-20-dedicated-network-between-services.md
_posts/2020-08-24-installation-requirements.md

and
faq/search_data.json
```

### Operating environment

all

**Comment by johnwalicki** [comment]
We have a better Search in the new theme and a more comprehensive FAQ at
https://open-horizon.github.io/docs/getting_started/faq/

**Comment by joewxboy** [comment]
![Image](https://user-images.githubusercontent.com/782091/225086553-6af68f98-5f5a-42ec-9d02-65ae6e45fe9e.png)

This link should be removed due to this push

**Comment by joewxboy** [comment]
Closing, fixed.
