### ISSUE TITLE
Refresh the component table

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#469]
There has been a tremendous amount of work done over the past several months.  The component table should be refreshed.
See
- https://open-horizon.github.io/docs/getting_started/components/

Here:
- https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/getting_started/components.md

Which resolves to this URL:
- https://open-horizon.github.io/docs/getting_started/components/

**Comment by joewxboy** [comment]
@bencourliss and @naphelps should this table be updated with every Thursday release?  And if so, is it possible to automate the table updates or does it need to be manually updated for some reason?

**Comment by naphelps** [comment]
I did not even know this was here. Not sure if this can be automated in some way.

**Comment by johnwalicki** [comment]
All good conversation.  I wasn't trying to create automation.  Just copy the component table versions that @Rene-Ch1 is assembling.

**Comment by johnwalicki** [comment]
The current component table is severly outdated.

**Comment by johnwalicki** [comment]
Mangled front matter
