### ISSUE TITLE
Better Slack link

### ISSUE THREAD

**Issue by andreas-ibm** [open-horizon/open-horizon.github.io#47]
**Describe the bug**
On the homepage (https://www.lfedge.org/projects/openhorizon/):

When I clicked on the “Discuss in Slack” link, https://lfedge.slack.com/archives/C011XLC1V2Q,  it just brought me to a sign-in page, which expected me to already be signed up to the LF Edge slack workspace, with no way of signing up.

It wasn’t until @joewxboy sent me a different link, https://join.slack.com/t/lfedge/shared_invite/zt-7kavdtmq-SeyFzM2CEABBcKYGEVCgkw, that I could actually join the workspace.  

I’d suggest using the latter link on the front-page to encourage new users. Alas I don't know how to get a Slack page that offers both options.

**To Reproduce**
1. Go to https://www.lfedge.org/projects/openhorizon/
2. Click on 'Discuss in Slack'
3. get prompted to log in, with no option to sign up.

**Expected behavior**
I expected a sign-up page, as people browsing from the homepage are more likely to be new users rather than already members.

**Screenshots**
N/A
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Vivaldi
 - Version: 3.6.2165.34

**Smartphone (please complete the following information):**
 N/A

**Additional context** (optional)
N/A

**Reading resources** (optional)
N/A

**Link to past related contributions** (optional)
N/A

**Deadline to solve the issue** (optional)
N/A

**Comment by joewxboy** [comment]
@andreas-ibm I spoke with our LF Edge resource and he suggested following the convention set by [Project EVE](https://www.lfedge.org/projects/eve/).  He then updated our project page.  Take a look at the project page now.  Does this solve the issue with first time visitors needing to sign up, others needing to log in, and finding a channel for the project?

**Comment by andreas-ibm** [comment]
That's perfect, and gives the channel name too!
