### ISSUE TITLE
Feature Request: Add /docs/developing/ pages to the OH navigation

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#470]
### Is your feature request related to a problem? Please describe.

Add this page to the OH navigation sidebar:

https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/developing/service_operators.md

**Comment by johnwalicki** [comment]
Four `developing` pages are missing:
```
model_management_system.md
service_containers.md
service_operators.md
transform_image.md
```
I stumbled over the fact that `transform_image.md` was missing a few weeks ago.  See https://github.com/open-horizon/open-horizon.github.io/issues/437

**Comment by joewxboy** [comment]
Do these pages also belong on the /docs home page in the Developing card?

**Comment by johnwalicki** [comment]
@joewxboy I'm working on the "Developing edge services" navigation and subnavigation.

 I have not touched /docs home page recently.

**Comment by johnwalicki** [comment]
I also found that the `using_edge_services/service_rollbacks.md` was not in the navigation.  I added that page as well.

**Comment by johnwalicki** [comment]
This turned out to be a bigger PR that I expected because I had to restructure the "developing edge services" nav and sub nav.

**Comment by johnwalicki** [comment]
I confirmed everything looks good with the navigation  / sub-navigation under the "Developing" section of 
https://open-horizon.github.io/docs/developing/

While I think the Further Reading for Devices and Clusters sub sections are somewhat unnecessary, I didn't spend the time to collapse those page indexes into the Devices or Cluster sub sections
