### ISSUE TITLE
Page Build GitHub Action fails

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#474]
Since Friday, the Open Horizon page build GHA is failing:
https://github.com/open-horizon/open-horizon.github.io/actions

This one failed:
https://github.com/open-horizon/open-horizon.github.io/actions/runs/4384544460

The last successfuly run:
https://github.com/open-horizon/open-horizon.github.io/actions/runs/4350292347

The error:
```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/just-the-docs-dark.scss':
    File to import not found or unreadable: ./vendor/OneDarkJekyll/syntax-one-dark-vivid. Load paths: /github/workspace/_sass /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass /tmp/jekyll-remote-theme-20230310-8-2ud9wp/_sass /usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_sass /tmp/jekyll-remote-theme-20230310-8-2ud9wp/_sass on line 20

**Comment by joewxboy** [comment]
It's also preventing the Orphan Checker and the standard page building from working.  This failure started about a week ago and may be based on a bad SCSS file used by the dark version of the Just the Docs theme:

```
 Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/just-the-docs-dark.scss':
                    File to import not found or unreadable: ./vendor/OneDarkJekyll/syntax-one-dark-vivid. Load paths: /Users/edge/dev/open-horizon.github.io/_sass /Users/edge/dev/open-horizon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-theme-primer-0.6.0/_sass /private/var/folders/1s/xp8lb2xj2sbb1r3pqtddk8yr0000gn/T/jekyll-remote-theme-20230313-71858-kr0f0f/_sass /Users/edge/dev/open-horizon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-theme-primer-0.6.0/_sass /private/var/folders/1s/xp8lb2xj2sbb1r3pqtddk8yr0000gn/T/jekyll-remote-theme-20230313-71858-kr0f0f/_sass on line 20
jekyll 3.9.3 | Error:  File to import not found or unreadable: ./vendor/OneDarkJekyll/syntax-one-dark-vivid.
Load paths:
  /Users/edge/dev/open-horizon.github.io/_sass
  /Users/edge/dev/open-horizon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-theme-primer-0.6.0/_sass
  /private/var/folders/1s/xp8lb2xj2sbb1r3pqtddk8yr0000gn/T/jekyll-remote-theme-20230313-71858-kr0f0f/_sass
  /Users/edge/dev/open-horizon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-theme-primer-0.6.0/_sass
  /private/var/folders/1s/xp8lb2xj2sbb1r3pqtddk8yr0000gn/T/jekyll-remote-theme-20230313-71858-kr0f0f/_sass on line 20
/Users/edge/dev/open-horizon.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: ./vendor/OneDarkJekyll/syntax-one-dark-vivid. (Jekyll::Converters::Scss::SyntaxError)
```

**Comment by joewxboy** [comment]
I'm trying to fix it with the Orphan Checker issue.

**Comment by johnwalicki** [comment]
Ok - thanks - maybe the issue was introduced in this PR?
https://github.com/open-horizon/open-horizon.github.io/pull/468

**Comment by joewxboy** [comment]
> Ok - thanks - maybe the issue was introduced in this PR? #468

I doubt it since it only modified a CSS color.  I suspect it was because we weren't pinned to a specific version of just-the-docs and they shipped a major update:  https://just-the-docs.github.io/just-the-docs/CHANGELOG/ going from 0.3.3 to 0.4.0 and then 0.4.1 in March.

I'll try using the newer sass from 0.4.1 and see if that fixes anything.

**Comment by joewxboy** [comment]
@johnwalicki OK, I think the problem with the theme was introduced with [this pull request to just-the-docs](https://github.com/just-the-docs/just-the-docs/pull/1166/files).  I've added just the files in that PR to our codebase and our build no longer breaks for me.  I don't know what might break as a consequence of this change.

**Comment by joewxboy** [comment]
@johnwalicki Should be fixed now.  Please confirm.

**Comment by johnwalicki** [comment]
@joewxboy  - Yes, the navigation looks great now.  Thanks for the build process fixes.  Closing this issue.
