### ISSUE TITLE
Documentation📄: Update the Support page

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#479]
### What is the current documentation state?

The current contents are not useful, and actually link to IBM support with the word "Open Horizon":
https://open-horizon.github.io/docs/troubleshoot/support/

Consider instead using content like this:
https://github.com/open-horizon#contact

**Comment by mukadas026** [comment]
@joewxboy please assign this to me

**Comment by joewxboy** [comment]
> @joewxboy please assign this to me

@mukadas026 You got it.  Let me know if you have any issues.

**Comment by mukadas026** [comment]
Alright, I'll let you know

**Comment by mukadas026** [comment]
@joewxboy please where can I find the support page?

**Comment by johnwalicki** [comment]
@mukadas026 
You can parse the URL https://open-horizon.github.io/docs/troubleshoot/support/ to find the location of the support page.  

You will need to edit this file:
- https://github.com/open-horizon/open-horizon.github.io/blob/master/docs/troubleshoot/support.md
