### ISSUE TITLE
Documentation📄: Convert /index.html to /index.md

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#495]
### What is the current documentation state?

Page is currently HTML but can be safely converted to Markdown.

**Comment by bajibpathan** [comment]
@joewxboy - Can you please assign this issue to me just in case if no one assigned yet?

**Comment by bajibpathan** [comment]
@joewxboy - It appears that @Mister246 already created a PR for this issue. Is there any outstanding thing that you'd like me to take? Please advise.

Thank you

**Comment by joewxboy** [comment]
> @joewxboy - It appears that @Mister246 already created a PR for this issue. Is there any outstanding thing that you'd like me to take? Please advise.

Sorry about the mixup, @bajibpathan 
We have 17 open issues that haven't been claimed or assigned.  If you're able to view the list here: https://github.com/orgs/open-horizon-services/projects/3. take a look at the `No Status` column on the left.  All of those should be fair game.

And if you want to chat with the team and ask questions, feel free to talk to us at https://chat.lfx.linuxfoundation.org/ where any chat room beginning with "open-horizon" is an official project channel.
