### ISSUE TITLE
Bug🐛: Remove "Intel" from the phrase "Intel FDO"

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#513]
### Describe the bug.

On https://open-horizon.github.io/docs/installing/fdo/ and possibly other pages, the FDO project is referred to as "Intel FDO".  This is incorrect, and the FDO project has requested that we change it to read merely "FDO" instead.

### Operating environment

n/a

**Comment by johnwalicki** [comment]
There are also references of `Intel` in https://github.com/open-horizon/FDO-support README

**Comment by johnwalicki** [comment]
The correct technique to fix this issue is to make edits in the `FDO-support` repo. There is a CopyDocs GHA that will copy the markdown files here.

FWIW, the incorrectly placed `docs/fdo/*.md` files should be deleted.  The live files are in `docs/fdo/docs` dir (via the GHA)

**Comment by joewxboy** [comment]
Submitted this PR: https://github.com/open-horizon/FDO-support/pull/47

**Comment by joewxboy** [comment]
Fixed by PR, closing
