### ISSUE TITLE
Documentation📄: Add LF Edge reference to documentation site

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#525]
### What is the current documentation state?

Add a new line in the footer file reading:

Open Horizon is a [Stage Two project](https://wiki.lfedge.org/display/LE/Stage+2%3A+Growth) at [LF Edge](https://www.lfedge.org/).

This will need to be added to the `_config.yml` file at the end of the `footer_content` property value.  You will need to convert the above to HTML and backslash escape any quote marks.

**Comment by dotarjun** [comment]
Hey, I'd like to be assigned to this so I can work on it.

**Comment by johnwalicki** [comment]
@dotarjun - Thanks! I've assigned this GitHub issue to you.

**Comment by johnwalicki** [comment]
@joewxboy - Do we need to link to the definition Stage Two growth project?

```
Open Horizon is a [LF Edge](https://www.lfedge.org/) Stage Two Growth project.
```

Comparing to https://buildpacks.io
