### ISSUE TITLE
Enhance documentation HTML page with MD template

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#53]
The index.html page in /docs of the `issue-40` branch does not automatically apply the page template.  Adding an empty frontmatter section to the very top of the HTML above the DOCTYPE declaration was enough to force the liquid templating ending to perform variable replacement, but it didn't apply the headers and footers.

The URL to view the page when previewing locally (`bundle exec jekyll serve`):
http://127.0.0.1:4000/docs/

**Comment by xiuleiyy** [comment]
@joewxboy I can not find the /docs folder in `issue-40` branch. Did I miss something？

**Comment by xiuleiyy** [comment]
ah, I see the /docs is in your PR https://github.com/open-horizon/open-horizon.github.io/pull/52
it's not merged yet.

**Comment by joewxboy** [comment]
> ah, I see the /docs is in your PR #52
> it's not merged yet.

Thanks for letting me know.  I've now merged it.

**Comment by rajpratyush** [comment]
@joewxboy sir I would like to work this issue. Please do guide me on this.

**Comment by joewxboy** [comment]
@rajpratyush I've assigned it to you.  Feel free to ask any questions you may have.  @xiuleiyy is one of the original architects on this templating approach, so he'll be able to explain the reasons behind any decisions that we've made.  Let us know when you think you know what approach you'd like to take to solve.

**Comment by rajpratyush** [comment]
Give me one day sir to analyze and go through it

**Comment by rajpratyush** [comment]
@xiuleiyy Can you tell me more on this issue ??

@joewxboy while I was browsing through the website the FAQ section seemed a little off to me. I think it needs revamping like the fonts especially in header.
![Screenshot (683)](https://user-images.githubusercontent.com/53184883/109375560-c13f6a00-78e3-11eb-9111-62359d699fd4.png)
Here the question is printed twice once in header and then in body which I think seems off to me. what I/ suggest here to put the topic in Header and the exact question in body. and whenever I go though a question the "posted by GitHub - username shows up which should be in body and as the same font as question. 
![Screenshot (682)](https://user-images.githubusercontent.com/53184883/109375556-ba185c00-78e3-11eb-8ae6-e85048566f8e.png)

similarly here there are too many different fonts which doesn't make it look so good. 
there is no place to ask a new question. and website itself lacks n contributing section. here is sample FAQ which matplotlib implements. I believe we could have a cleaner interface like this.
![Screenshot (685)](https://user-images.githubusercontent.com/53184883/109375704-d963b900-78e4-11eb-84e3-d13723549fca.png)
![Screenshot (686)](https://user-images.githubusercontent.com/53184883/109375709-de286d00-78e4-11eb-9cbe-c40939f27126.png)

**Comment by rajpratyush** [comment]
@ joe another thing i saw we have a contributing guideline but it is inside overview for developer who wishes to contribute it should be accessible easily it should not take him to find out  hence I propose taking out common requests section from the quick starts and making them as tabs in header where it is easily available for the end user as well as developer. and either merging quick start with home or adding some more information in quick start.

**Comment by joewxboy** [comment]
> While I was browsing through the website the FAQ section seemed a little off to me. I think it needs revamping like the fonts especially in header.

Agreed, and the header is a little too tall.  Ideally, it should never take up more than 20% of the page height, and usually around 10%.  Also, it should be consistent between pages.  BTW, please preview with both desktop browsers and simulated or actual mobile browsers since the page uses responsive (and adaptive) web design.

> Here the question is printed twice once in header and then in body which I think seems off to me. 

Yes, good observation.

> what I/ suggest here to put the topic in Header and the exact question in body. and whenever I go though a question the "posted by GitHub - username shows up which should be in body and as the same font as question.

Sounds good.  Please also check the source code to confirm that we have `og` tags for machine readers and SEO and that they're populated correctly.

> similarly here there are too many different fonts which doesn't make it look so good.

Good point.  And the proportional size between the two is off.

> There is no place to ask a new question. 

True.  What would you recommend since this is a static site and we have no CGI to process user input.  Send them to a Slack channel to ask a question?  Or post the question in a GitHub discussion topic?  Or something else?

> and website itself lacks a contributing section to guide people how they can contribute to open horizon projects. 

One important thing we're missing is a lightweight `CONTRIBUTING.md` file in each repo.  We're actually "required" to have that by best practices, but I don't want to repeat too much information there and in the web docs.  I'm thinking that we have minimal info in the CONTRIBUTING.md file and then a link to the canonical web page.  What do you think?

> and for now since there are not much FAQs in the FAQ section I think the search bar can be dropped not from codebase but from rendering it like commenting the code so that later we can use it.

And we actually have a lot of questions in Slack that have been answered that could be added to the FAQ section. :)

> here is sample FAQ which matplotlib implements. I believe we could have a cleaner interface like this.

That's better looking than what we currently have, thanks.

**Comment by rajpratyush** [comment]
@joewxboy @xiuleiyy when I ran the code 
`bundle exec jekyll serve`
 This was the message in got in command prompt
 
![Screenshot (688)](https://user-images.githubusercontent.com/53184883/109614172-4a5ed700-7b58-11eb-9f5f-ae8e4e4de345.png)

This was the output when I ran the website on the browser 
`http://127.0.0.1:4000/docs/`

![Screenshot (689)](https://user-images.githubusercontent.com/53184883/109614349-86923780-7b58-11eb-97fc-f8c7040e1744.png)


Am I able to reproduce the issue correctly ?

**Comment by joewxboy** [comment]
@rajpratyush Yes, you now have it running correctly.

You saw two types of warning messages related to rendering web pages (but not related to running `Jekyll serve`):
1. Items like JS files that a web page referred to, but do not exist in your local filesystem.  This is a problem in the web page that will need to be fixed.  The favicon.ico missing message is similar, except triggered by the browser instead of a web page.
2. Variables in a MD file that are invalid.  Variables follow the pattern `{{ var.name.here }}` and variable names should not begin with a dot.  The warning messages refer to bad variable references that can be safely deleted.

In both cases, the warnings do not impact the rendering of the pages, nor do they result in garbage characters being inserted into the resulting pages.  Therefore, fixing those hasn't been as high a priority as other issues.

**Comment by rajpratyush** [comment]
@joewxboy 
yes sir jekyll serve was working correctly. but I was not able to understand why our header and footer were ignored from rendering. the code was as per the syntax but I wasn't able to understand it
