### ISSUE TITLE
Enhance Swagger JSON files with JavaScript template

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#54]
In the `issue-40` branch, the /api folder has three "json" files:
```
└── api
    ├── exchange_swagger.json
    ├── mms_swagger.json
    └── sdo_swagger.json
```
You may need to create a new page template, based on "page", that will add the appropriate code to render the JSON properly.
The end result should look and function like: https://www.ibm.com/support/knowledgecenter/SSFKVV_4.2/api/sdo_swagger.json

**Comment by shubhank-saxena** [comment]
@joewxboy can I pick this up?

**Comment by joewxboy** [comment]
@shubhank-saxena You got it!  Thanks.  When you've figured out how you're going to tackle it, please run it by me.

**Comment by shubhank-saxena** [comment]
Thank you for the assignment @joewxboy 
These are the steps I have figured out -
- We add the dist folder of swagger-UI in our project as it contains bare-bones UI for swagger docs (https://github.com/swagger-api/swagger-ui/tree/master/dist)
- Then we add a swagger rendering plugin that locates the UI bundle and tries to render it.
- Then we include a fluid import of the same.
- And finally, create a page with format import like this `{% swagger /api/my-api.json %}`

**Comment by joewxboy** [comment]
Excellent, thanks.  Let's see if it makes sense to add the list folder of the swagger-UI to the `open-horizon.github.io` repo in the root folder, rather than under "/docs" if possible.  Go ahead and see if you can get it working. :)

**Comment by shubhank-saxena** [comment]
Hello @joewxboy 
I tried the approach as I mentioned above. I created a custom fluid tag and added it in _plugins folder, but unfortunately, I am still not able to access it.
I am relatively new to Jekyll, so is there something that I am missing on?

**Comment by joewxboy** [comment]
OK, I'm assuming the steps you implemented were:
1. Clone the `open-horizon.github.io` repo locally
2. `cd open-horizon.github.io`
3. `bundle install`
4. `bundle exec jekyll serve` # to preview locally
5. `git clone` of "swagger-ui/tree/master/dist" to a folder under the open-horizon.github.io tree, maybe "swagger-ui"
6. Create a custom Liquid tag plugin in `_plugins`
7. Import the tag
8. Create a page and import the swagger JSON file

Are those the basic steps you followed?  If not, where did you get stuck?

**Comment by shubhank-saxena** [comment]
Yes. These are the exact steps that I followed. 
After this, I am getting the following error -
`Liquid syntax error (line 1): Unknown tag 'swagger' (Liquid::SyntaxError)`
This error arises in the page which uses the new liquid tag

**Comment by joewxboy** [comment]
OK, what does your custom liquid tag look like (step 6)?
