### ISSUE TITLE
Add instructions for installation on QEMU VMs

### ISSUE THREAD

**Issue by mounaiban** [open-horizon/open-horizon.github.io#56]
Hi, I would like to add instructions for setting up the all-in-one Open Horizon evaluation host using QEMU virtual machines, for those who prefer using this wonderful little VMM, but I am not sure where to add them.

Should I expand the existing ``common-requests/install.md``, or would creating a new page, and calling it something like ``install-qemu.md``, be a better way to do this? (keeping in mind that someone else might want to add other VMMs like VMWare, HyperV... in the future)

**Comment by bmpotter** [comment]
@mounaiban i think this info should be under https://github.com/open-horizon/devops/tree/master/mgmt-hub and linked to in  open-horizon.github.io . I'll assigned this issue to you.

**Comment by mounaiban** [comment]
After looking through the site, I thought it would be best to put this in the FAQ section (under [``/_posts``](https://github.com/open-horizon/open-horizon.github.io/tree/master/_posts)). There would also be a link from ``common-requests/install.md`` to the FAQ post.

I haven't ruled out adding to the existing installation instructions in the devops repository, I'm just leaving that for a separate issue.

**Comment by joewxboy** [comment]
All the work is now being performed in devops#102 so closing this one.
