### ISSUE TITLE
Documentation: Improve parent - child navigation for Edge Cluster pages

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#572]
### What is the current documentation state?

Related to Issue #564  and PR #571 ,  the new pages do not appear in the navigation. The fix is to add the appropriate `grand_parent:` to those updated pages:
- install_k3s_edge_cluster.md
- install_microk8s_edge_cluster.md
-  install_ocp_edge_cluster.md

**Comment by joewxboy** [comment]
Thanks!  fast work. :)
