### ISSUE TITLE
Documentation📄: Configuring k3s and microk8s

### ISSUE THREAD

**Issue by adhishreekadam** [open-horizon/open-horizon.github.io#574]
### What is the current documentation state?

The page https://open-horizon.github.io/docs/anax/docs/cluster_install/ is missing the steps to form the config files for k3s and microk8s. 

### Proposed Statement

For microk8s add the two commands maybe after step 3b in the microk8s section:
`cd .kube`
 `microk8s config > config` 

For k3s add the command maybe after step 1h in the k3s section:
`/etc/rancher/k3s/k3s.yaml as ~/.kube/config`

**Comment by szeyan543** [comment]
Hi @joewxboy Could you assign this to me? Thank you

**Comment by joewxboy** [comment]
> Hi @joewxboy Could you assign this to me? Thank you

You got it!

**Comment by joewxboy** [comment]
Fixed, closing.
