### ISSUE TITLE
Create GHA to scan open-horizon.github.io for orphaned pages

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#89]
As @dabooz [pointed out](https://matrix.to/#/!tUVxmZVqTyIhSrlIjN:chat.lfx.linuxfoundation.org/$A30DO_4--NA3IO1gZcFF5ODPyyEjZ4RQM24zRtXuK4o?via=chat.lfx.linuxfoundation.org) in the Documentation WG chat room, we have several pages in the documentation repo that do not have navigable links to their URL.  These are considered "orphan pages" because they do not have parents or siblings in the navigation tree.  Let's find or create a GitHub Action to find orphaned pages and automatically open an issue to address them.

**Comment by MOLOCH-dev** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by tushar5526** [comment]
Hi, this seems a good problem to work on. Could you assign it to me assuming the issue has been stagnant for some time?

**Comment by joewxboy** [comment]
@tushar5526 You got it.  Let me know if you have any questions.

**Comment by tushar5526** [comment]
`Let's find or create a GitHub Action to find orphaned pages and automatically open an issue to address them`

Yes. A few things before starting out. 

- When the GHA will run, should it be some manual command that executes the GHA to run for that specific PR.
- or assuming we will be running the GHA for each PR to check for orphan pages (due to changes of the PR) might lead to multiple issues cluttering the repository.

A heads-up on the lifecycle of the action would help me get things better.

**Comment by joewxboy** [comment]
Good points, @tushar5526 .  I'm thinking we'll likely want to trigger it manually, and on a schedule.

The current link checker GHA runs once a month and that seems just about right for now.  Let's try that here as well.

Bonus points if we can figure out how a committer can manually run it on their branch before creating a PR.

**Comment by tushar5526** [comment]
Hey @joewxboy

https://talk.jekyllrb.com/t/finding-asset-and-other-orphans/3777/2

I tried searching and found a few ways but the above method seems the best way to do it. 

I am thinking of implementing this in a GHA, or if you have any other ideas to implement this if you would like to share.

**Comment by joewxboy** [comment]
Hmm, I'm currently using https://github.com/open-horizon/open-horizon.github.io/blob/master/.github/workflows/Check_broken_link.yml to check for broken hyperlinks.  I wonder if the same code (or something similar) could also be used to check for orphans?

**Comment by tushar5526** [comment]
https://raw.githubusercontent.com/victoriadrake/hydra-link-checker/master/hydra.py
Behind the scene, `linksnitch` GHA is using this script which basically crawls the webpage and checks if there is a broken link, but in the case of orphan pages we don't have any links to that page so we basically cant crawl an orphan page. 

One should know the exact url of the orphan page to visit it.

`wget` could be used to recursively download the whole website, or the web pages reachable and then we could compare it with the `_site` build that is generated by the command `bundle exec jekyll build`.

I hope I am not getting something wrong :p, would like to hear your thoughts.

PS: I might write a python script if `wget` is not able to do the job properly, but for now `wget` seems fine.

**Comment by tushar5526** [comment]
Sure. I will update you soon. Thanks

**Comment by tushar5526** [comment]
```
Only in ../_site/: dir.html
Only in ../_site/docs/cli: hzn_cli.html
Only in ../_site/docs/cli: index.html
Only in ../_site/docs/developing: container_deployment_options.html
Only in ../_site/docs/developing: further_reading_devices.html
Only in ../_site/docs/getting_started: accessibility.html
Only in ../_site/docs/getting_started: components.html
Only in ../_site/docs/getting_started: known_issues.html
Only in ../_site/docs/getting_started: release_notes.html
Only in ../_site/docs/hub: overview.html
Only in ../_site/docs/hub: prerequisites.html
Only in ../_site/docs/installing: exchange_api.html
Only in ../_site/docs: SUMMARY.html
Only in ../_site/docs/troubleshoot: index.html
Only in ../_site/docs/user_management: certificates.html
Only in ../_site/docs/user_management: disaster_recovery.html
Only in ../_site/docs/user_management: monitoring_infrastructure.html
Only in ../_site/swagger-ui: oauth2-redirect.html
```

I am able to get this output using Linux command-line tools. 

It is properly listing `Only in ../_site/docs/getting_started: known_issues.html` as mentioned by *dabooz* [link](https://matrix.to/#/!tUVxmZVqTyIhSrlIjN:chat.lfx.linuxfoundation.org/$A30DO_4--NA3IO1gZcFF5ODPyyEjZ4RQM24zRtXuK4o?via=chat.lfx.linuxfoundation.org).

The output looks good to me, would love @joewxboy if you could spot any discrepancy or false positives.

Thanks

**Comment by joewxboy** [comment]
I didn't expect so many orphans, but that's probably a correct list.

**Comment by tushar5526** [comment]
@joewxboy I am thinking of running this GHA on a schedule monthly and also providing a way to run the action manually on PRs using [ChatOps](https://github.com/peter-evans/slash-command-dispatch).

`Bonus points if we can figure out how a committer can manually run it on their branch before creating a PR.`
One can use the `ChatOps` to run the action on their fork on their PR too.

I will go ahead and implement it, if it seems fine to you.

**Comment by joewxboy** [comment]
ChatOps is a valuable concept.  However, some of this approach appears to potentially clutter the issue or PR comments.  On the other hand, we've been wanting to integrate ChatOps with our Matrix chat server.  Can we begin a GitHub Discussion on this topic?  We can discuss options, pros and cons, and results of research.  Also, let's discuss potential commands that people would want to use.

**Comment by tushar5526** [comment]
>some of this approach appears to potentially clutter the issue or PR comments
Instead of Outputting the orphan pages in a comment of a PR, we could just log it in the GHA's log. Similar to how the broken-link checker works.

>we've been wanting to integrate ChatOps with our Matrix chat server
I will be happy to do it and we can start a discussion on it.

For the time being, I think running orphan pages GHA on a schedule (just like the broken-link checker) will do the job. So I am thinking of going ahead with it?

**Comment by joewxboy** [comment]
> For the time being, I think running orphan pages GHA on a schedule (just like the broken-link checker) will do the job. So I am thinking of going ahead with it?

Yes, please.
