### ISSUE TITLE
Move "open in new tab" SVG from HTML to CSS

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/open-horizon.github.io#91]
**Describe the bug**
SVG is currently embedded in the HTML and needs to be removed.

**Expected behavior**
The links should still open in a new tab, and the icon should be present.  Use CSS and a class to insert expected behavior, not .md or .html

**Comment by joewxboy** [comment]
The first task would be to identify all candidate links in the HTML/Markdown.  We'd want to remove the inline SVG image and ensure the hyperlink anchor tag had a class specifically for this purpose (ex. class="externalLink").
Second, we'd identify CSS that's on all or most pages, put it on all pages, and add a selector that appends the SVG to all anchor tags with that class.
Third, we'd do the same with JavaScript and target an onclick event handler that would ensure the link opens in a new tab when clicked on.
Those three tasks, when used in combination, would replicate the current functionality while at the same time ensuring that all downstream consumers of the Markdown/HTML documentation do not inherit that functionality.

**Comment by Rene-Ch1** [comment]
Slack on 9/1:

Joe Pearson  27 minutes ago
The first task would be to identify all candidate links in the HTML/Markdown.  We'd want to remove the inline SVG image and ensure the hyperlink anchor tag had a class specifically for this purpose (ex. class="externalLink").
Second, we'd identify CSS that's on all or most pages, put it on all pages, and add a selector that appends the SVG to all anchor tags with that class.
Third, we'd do the same with JavaScript and target an onclick event handler that would ensure the link opens in a new tab when clicked on.
Those three tasks, when used in combination, would replicate the current functionality while at the same time ensuring that all downstream consumers of the Markdown/HTML documentation do not inherit that functionality.

**Comment by Sukriti-sood** [comment]
@joewxboy  Can you elaborate a bit about which SVG you are mentioning?

**Comment by Rene-Ch1** [comment]
I think that it's the SVG for this:

![image](https://user-images.githubusercontent.com/53276773/152567909-e46e6209-7571-4e48-b82b-c54122806479.png)

**Comment by Sukriti-sood** [comment]
@Rene-Ch1 Thanks

**Comment by joewxboy** [comment]
@Sukriti-sood And if it's unclear ... IEAM (IBM Edge Application Manager) is a downstream commercial distribution based on the OH (Open Horizon) project.  We're attempting to make the IEAM-contributed documentation vendor-neutral and yet consumable by any downstream product that wants to use it.
